// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: common/common.proto

package common

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type SsoSecureInfo struct {
	SecSign  []byte `protobuf:"bytes,1,opt"`
	SecToken []byte `protobuf:"bytes,2,opt"`
	SecExtra []byte `protobuf:"bytes,3,opt"`
}

type SsoReserveFields struct {
	ClientIpCookie []byte               `protobuf:"bytes,8,opt"`
	Flag           proto.Option[uint32] `protobuf:"varint,9,opt"`
	EnvId          proto.Option[uint32] `protobuf:"varint,10,opt"`
	LocaleId       proto.Option[uint32] `protobuf:"varint,11,opt"`
	Qimei          proto.Option[string] `protobuf:"bytes,12,opt"`
	Env            []byte               `protobuf:"bytes,13,opt"`
	NewConnFlag    proto.Option[uint32] `protobuf:"varint,14,opt"`
	TraceParent    proto.Option[string] `protobuf:"bytes,15,opt"`
	Uid            proto.Option[string] `protobuf:"bytes,16,opt"`
	Imsi           proto.Option[uint32] `protobuf:"varint,18,opt"`
	NetworkType    proto.Option[uint32] `protobuf:"varint,19,opt"`
	IpStackType    proto.Option[uint32] `protobuf:"varint,20,opt"`
	MsgType        proto.Option[uint32] `protobuf:"varint,21,opt"`
	TrpcRsp        proto.Option[string] `protobuf:"bytes,22,opt"`
	TransInfo      map[string]string    `protobuf:"bytes,23,rep" protobuf_key:"bytes,1,opt" protobuf_val:"bytes,2,opt"`
	SecInfo        *SsoSecureInfo       `protobuf:"bytes,24,opt"`
	SecSigFlag     proto.Option[uint32] `protobuf:"varint,25,opt"`
	NtCoreVersion  proto.Option[uint32] `protobuf:"varint,26,opt"`
	SsoRouteCost   proto.Option[uint32] `protobuf:"varint,27,opt"`
	SsoIpOrigin    proto.Option[uint32] `protobuf:"varint,28,opt"`
	PresureToken   []byte               `protobuf:"bytes,30,opt"`
}
