// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: common/inc_pull.proto

package common

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type IncPullRequest struct {
	ReqCount            proto.Option[uint32] `protobuf:"varint,2,opt"`
	Time                proto.Option[int64]  `protobuf:"varint,3,opt"`
	LocalSeq            proto.Option[uint32] `protobuf:"varint,4,opt"`
	Cookie              []byte               `protobuf:"bytes,5,opt"`
	Flag                proto.Option[int32]  `protobuf:"varint,6,opt"`
	ProxySeq            proto.Option[uint32] `protobuf:"varint,7,opt"`
	RequestBiz          []*IncPullRequestBiz `protobuf:"bytes,10001,rep"`
	ExtSnsFlagKey       []uint32             `protobuf:"varint,10002,rep"`
	ExtPrivateIdListKey []uint32             `protobuf:"varint,10003,rep"`
}

type IncPullRequestBiz struct {
	BizType proto.Option[int32]    `protobuf:"varint,1,opt"`
	BizData *IncPullRequestBizBusi `protobuf:"bytes,2,opt"`
	_       [0]func()
}

type IncPullRequestBizBusi struct {
	ExtBusi []int32 `protobuf:"varint,1,rep"`
}

type IncPullResponse struct {
	Seq        proto.Option[uint32]       `protobuf:"varint,1,opt"`
	Cookie     []byte                     `protobuf:"bytes,2,opt"`
	IsEnd      proto.Option[bool]         `protobuf:"varint,3,opt"`
	Time       proto.Option[int64]        `protobuf:"varint,6,opt"`
	SelfUin    proto.Option[int64]        `protobuf:"varint,7,opt"`
	SmallSeq   proto.Option[uint32]       `protobuf:"varint,8,opt"`
	FriendList []*IncPullResponseFriend   `protobuf:"bytes,101,rep"`
	Category   []*IncPullResponseCategory `protobuf:"bytes,102,rep"`
}

type IncPullResponseFriend struct {
	Uid        proto.Option[string]             `protobuf:"bytes,1,opt"`
	CategoryId proto.Option[int32]              `protobuf:"varint,2,opt"`
	Uin        proto.Option[int64]              `protobuf:"varint,3,opt"`
	SubBiz     map[int32]*IncPullResponseSubBiz `protobuf:"bytes,10001,rep" protobuf_key:"varint,1,opt" protobuf_val:"bytes,2,opt"`
}

type IncPullResponseSubBiz struct {
	NumData map[int32]int32  `protobuf:"bytes,1,rep" protobuf_key:"varint,1,opt" protobuf_val:"varint,2,opt"`
	Data    map[int32]string `protobuf:"bytes,2,rep" protobuf_key:"varint,1,opt" protobuf_val:"bytes,2,opt"`
}

type IncPullResponseCategory struct {
	CategoryId          proto.Option[int32]  `protobuf:"varint,1,opt"`
	CategoryName        proto.Option[string] `protobuf:"bytes,2,opt"`
	CategoryMemberCount proto.Option[int32]  `protobuf:"varint,3,opt"`
	CatogorySortId      proto.Option[int32]  `protobuf:"varint,4,opt"`
	_                   [0]func()
}
