// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: common/kick_nt.proto

package common

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type KickNTReq struct {
	Uin          proto.Option[int64]  `protobuf:"varint,1,opt"`
	IsSameDevice proto.Option[bool]   `protobuf:"varint,2,opt"`
	TipsInfo     proto.Option[string] `protobuf:"bytes,3,opt"`
	TipsTitle    proto.Option[string] `protobuf:"bytes,4,opt"`
	_            [0]func()
}
