// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/oidb/acidify_code_oidb_0x9154_1.proto

package oidb

type FetchFaceDetailsReq struct {
	Field1 uint32 `protobuf:"varint,1,opt"`
	Field2 uint32 `protobuf:"varint,2,opt"`
	Field3 string `protobuf:"bytes,3,opt"`
	_      [0]func()
}

type FetchFaceDetailsResp struct {
	Field1           uint32                             `protobuf:"varint,1,opt"`
	CommonFace       *FetchFaceDetailsContent           `protobuf:"bytes,2,opt"` // 普通表情
	SpecialBigFace   *FetchFaceDetailsContent           `protobuf:"bytes,3,opt"` // 大表情
	SpecialMagicFace *FetchFaceDetailsMagicEmojiContent `protobuf:"bytes,4,opt"` // 魔法表情
	_                [0]func()
}

type FetchFaceDetailsContent struct {
	EmojiList   []*FetchFaceDetailsContent_FetchFaceDetailsEmojiList `protobuf:"bytes,1,rep"`
	ResourceUrl *FetchFaceDetailsResourceUrl                         `protobuf:"bytes,2,opt"`
}

type FetchFaceDetailsMagicEmojiContent struct {
	Magic       *FetchFaceDetailsMagicEmojiContent_FetchFaceDetailsMagicEmojiList `protobuf:"bytes,1,opt"`
	ResourceUrl *FetchFaceDetailsResourceUrl                                      `protobuf:"bytes,2,opt"`
	_           [0]func()
}

type FetchFaceDetailsResourceUrl struct {
	BaseUrl string `protobuf:"bytes,1,opt"`
	AdvUrl  string `protobuf:"bytes,2,opt"`
	_       [0]func()
}

type FetchFaceDetailsEmoji struct {
	QSid             string                       `protobuf:"bytes,1,opt"`
	QDes             string                       `protobuf:"bytes,2,opt"`
	EmCode           string                       `protobuf:"bytes,3,opt"`
	QCid             uint32                       `protobuf:"varint,4,opt"`
	AniStickerType   uint32                       `protobuf:"varint,5,opt"`
	AniStickerPackId uint32                       `protobuf:"varint,6,opt"`
	AniStickerId     uint32                       `protobuf:"varint,7,opt"`
	Url              *FetchFaceDetailsResourceUrl `protobuf:"bytes,8,opt"`
	EmojiNameAlias   []string                     `protobuf:"bytes,9,rep"`
	Unknown10        uint32                       `protobuf:"varint,10,opt"`
	AniStickerWidth  uint32                       `protobuf:"varint,13,opt"`
	AniStickerHeight uint32                       `protobuf:"varint,14,opt"`
}

type FetchFaceDetailsContent_FetchFaceDetailsEmojiList struct {
	PackName string                   `protobuf:"bytes,1,opt"`
	Detail   []*FetchFaceDetailsEmoji `protobuf:"bytes,2,rep"`
}

type FetchFaceDetailsMagicEmojiContent_FetchFaceDetailsMagicEmojiList struct {
	EmojiList []*FetchFaceDetailsEmoji `protobuf:"bytes,2,rep"`
}
