// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/oidb/ntv2_rich_media.proto

package oidb

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type NTV2RichMediaHighwayExt struct {
	FileUuid    proto.Option[string] `protobuf:"bytes,1,opt"`
	UKey        proto.Option[string] `protobuf:"bytes,2,opt"`
	Network     *NTHighwayNetwork    `protobuf:"bytes,5,opt"`
	MsgInfoBody []*MsgInfoBody       `protobuf:"bytes,6,rep"`
	BlockSize   proto.Option[uint32] `protobuf:"varint,10,opt"`
	Hash        *NTHighwayHash       `protobuf:"bytes,11,opt"`
}

type NTHighwayHash struct {
	FileSha1 [][]byte `protobuf:"bytes,1,rep"`
}

type NTHighwayNetwork struct {
	IPv4S []*NTHighwayIPv4 `protobuf:"bytes,1,rep"`
}

type NTHighwayIPv4 struct {
	Domain *NTHighwayDomain     `protobuf:"bytes,1,opt"`
	Port   proto.Option[uint32] `protobuf:"varint,2,opt"`
	_      [0]func()
}

type NTHighwayDomain struct {
	IsEnable proto.Option[bool]   `protobuf:"varint,1,opt"`
	Ip       proto.Option[string] `protobuf:"bytes,2,opt"`
	_        [0]func()
}

type NTV2RichMediaReq struct {
	ReqHead          *MultiMediaReqHead   `protobuf:"bytes,1,opt"`
	Upload           *UploadReq           `protobuf:"bytes,2,opt"`
	Download         *DownloadReq         `protobuf:"bytes,3,opt"`
	DownloadRKey     *DownloadRKeyReq     `protobuf:"bytes,4,opt"`
	Delete           *DeleteReq           `protobuf:"bytes,5,opt"`
	UploadCompleted  *UploadCompletedReq  `protobuf:"bytes,6,opt"`
	MsgInfoAuth      *MsgInfoAuthReq      `protobuf:"bytes,7,opt"`
	UploadKeyRenewal *UploadKeyRenewalReq `protobuf:"bytes,8,opt"`
	DownloadSafe     *DownloadSafeReq     `protobuf:"bytes,9,opt"`
	Extension        []byte               `protobuf:"bytes,99,opt"`
}

type MultiMediaReqHead struct {
	Common *CommonHead `protobuf:"bytes,1,opt"`
	Scene  *SceneInfo  `protobuf:"bytes,2,opt"`
	Client *ClientMeta `protobuf:"bytes,3,opt"`
	_      [0]func()
}

type CommonHead struct {
	RequestId proto.Option[uint32] `protobuf:"varint,1,opt"`
	Command   proto.Option[uint32] `protobuf:"varint,2,opt"`
	_         [0]func()
}

type SceneInfo struct {
	RequestType  proto.Option[uint32] `protobuf:"varint,101,opt"`
	BusinessType proto.Option[uint32] `protobuf:"varint,102,opt"`
	SceneType    proto.Option[uint32] `protobuf:"varint,200,opt"`
	C2C          *C2CUserInfo         `protobuf:"bytes,201,opt"`
	Group        *GroupInfo           `protobuf:"bytes,202,opt"`
	_            [0]func()
}

type C2CUserInfo struct {
	AccountType proto.Option[uint32] `protobuf:"varint,1,opt"`
	TargetUid   proto.Option[string] `protobuf:"bytes,2,opt"`
	_           [0]func()
}

type GroupInfo struct {
	GroupUin proto.Option[int64] `protobuf:"varint,1,opt"`
	_        [0]func()
}

type ClientMeta struct {
	AgentType proto.Option[uint32] `protobuf:"varint,1,opt"`
	_         [0]func()
}

type DownloadReq struct {
	Node     *IndexNode   `protobuf:"bytes,1,opt"`
	Download *DownloadExt `protobuf:"bytes,2,opt"`
	_        [0]func()
}

type IndexNode struct {
	Info       *FileInfo            `protobuf:"bytes,1,opt"`
	FileUuid   proto.Option[string] `protobuf:"bytes,2,opt"`
	StoreId    proto.Option[uint32] `protobuf:"varint,3,opt"`
	UploadTime proto.Option[uint32] `protobuf:"varint,4,opt"`
	Ttl        proto.Option[uint32] `protobuf:"varint,5,opt"`
	SubType    proto.Option[uint32] `protobuf:"varint,6,opt"`
	_          [0]func()
}

type FileInfo struct {
	FileSize proto.Option[uint32] `protobuf:"varint,1,opt"`
	FileHash proto.Option[string] `protobuf:"bytes,2,opt"`
	FileSha1 proto.Option[string] `protobuf:"bytes,3,opt"`
	FileName proto.Option[string] `protobuf:"bytes,4,opt"`
	Type     *FileType            `protobuf:"bytes,5,opt"`
	Width    proto.Option[uint32] `protobuf:"varint,6,opt"`
	Height   proto.Option[uint32] `protobuf:"varint,7,opt"`
	Time     proto.Option[uint32] `protobuf:"varint,8,opt"`
	Original proto.Option[uint32] `protobuf:"varint,9,opt"`
	_        [0]func()
}

type FileType struct {
	Type        proto.Option[uint32] `protobuf:"varint,1,opt"`
	PicFormat   proto.Option[uint32] `protobuf:"varint,2,opt"`
	VideoFormat proto.Option[uint32] `protobuf:"varint,3,opt"`
	VoiceFormat proto.Option[uint32] `protobuf:"varint,4,opt"`
	_           [0]func()
}

type DownloadExt struct {
	Pic   *PicDownloadExt   `protobuf:"bytes,1,opt"`
	Video *VideoDownloadExt `protobuf:"bytes,2,opt"`
	Ptt   *PttDownloadExt   `protobuf:"bytes,3,opt"`
	_     [0]func()
}

type VideoDownloadExt struct {
	BusiType    proto.Option[uint32] `protobuf:"varint,1,opt"`
	SceneType   proto.Option[uint32] `protobuf:"varint,2,opt"`
	SubBusiType proto.Option[uint32] `protobuf:"varint,3,opt"`
	_           [0]func()
}

type PicDownloadExt struct {
	_ [0]func()
}

type PttDownloadExt struct {
	_ [0]func()
}

type PicUrlExtInfo struct {
	OriginalParameter proto.Option[string] `protobuf:"bytes,1,opt"`
	BigParameter      proto.Option[string] `protobuf:"bytes,2,opt"`
	ThumbParameter    proto.Option[string] `protobuf:"bytes,3,opt"`
	_                 [0]func()
}

type VideoExtInfo struct {
	VideoCodecFormat proto.Option[uint32] `protobuf:"varint,1,opt"`
	_                [0]func()
}

type MsgInfo struct {
	MsgInfoBody []*MsgInfoBody `protobuf:"bytes,1,rep"`
	ExtBizInfo  *ExtBizInfo    `protobuf:"bytes,2,opt"`
}

type MsgInfoBody struct {
	Index     *IndexNode         `protobuf:"bytes,1,opt"`
	Picture   *PictureInfo       `protobuf:"bytes,2,opt"`
	Video     *VideoInfo         `protobuf:"bytes,3,opt"`
	Audio     *AudioInfo         `protobuf:"bytes,4,opt"`
	FileExist proto.Option[bool] `protobuf:"varint,5,opt"`
	HashSum   *HashSum           `protobuf:"bytes,6,opt"`
	_         [0]func()
}

type HashSum struct {
	PbReserveC2C *C2CSource   `protobuf:"bytes,201,opt"` // bytes
	TroopSource  *TroopSource `protobuf:"bytes,202,opt"`
	_            [0]func()
}

type C2CSource struct {
	FriendUid proto.Option[string] `protobuf:"bytes,2,opt"`
	_         [0]func()
}

type TroopSource struct {
	GroupUin proto.Option[uint32] `protobuf:"varint,1,opt"`
	_        [0]func()
}

type VideoInfo struct {
	_ [0]func()
}

type AudioInfo struct {
	_ [0]func()
}

type PictureInfo struct {
	UrlPath proto.Option[string] `protobuf:"bytes,1,opt"`
	Ext     *PicUrlExtInfo       `protobuf:"bytes,2,opt"`
	Domain  proto.Option[string] `protobuf:"bytes,3,opt"`
	_       [0]func()
}

type ExtBizInfo struct {
	Pic      *PicExtBizInfo       `protobuf:"bytes,1,opt"`
	Video    *VideoExtBizInfo     `protobuf:"bytes,2,opt"`
	Ptt      *PttExtBizInfo       `protobuf:"bytes,3,opt"`
	BusiType proto.Option[uint32] `protobuf:"varint,10,opt"`
	_        [0]func()
}

type PttExtBizInfo struct {
	SrcUin          proto.Option[uint64] `protobuf:"varint,1,opt"`
	PttScene        proto.Option[uint32] `protobuf:"varint,2,opt"`
	PttType         proto.Option[uint32] `protobuf:"varint,3,opt"`
	ChangeVoice     proto.Option[uint32] `protobuf:"varint,4,opt"`
	Waveform        []byte               `protobuf:"bytes,5,opt"`
	AutoConvertText proto.Option[uint32] `protobuf:"varint,6,opt"`
	Reserve         []byte               `protobuf:"bytes,11,opt"`
	PbReserve       []byte               `protobuf:"bytes,12,opt"`
	GeneralFlags    []byte               `protobuf:"bytes,13,opt"`
}

type VideoExtBizInfo struct {
	FromScene proto.Option[uint32] `protobuf:"varint,1,opt"`
	ToScene   proto.Option[uint32] `protobuf:"varint,2,opt"`
	PbReserve []byte               `protobuf:"bytes,3,opt"`
}

type PicExtBizInfo struct {
	BizType        proto.Option[uint32] `protobuf:"varint,1,opt"`
	TextSummary    proto.Option[string] `protobuf:"bytes,2,opt"`
	PbReserveC2C   []byte               `protobuf:"bytes,11,opt"`
	PbReserveTroop []byte               `protobuf:"bytes,12,opt"`
	FromScene      proto.Option[uint32] `protobuf:"varint,1001,opt"`
	ToScene        proto.Option[uint32] `protobuf:"varint,1002,opt"`
	OldFileId      proto.Option[uint32] `protobuf:"varint,1003,opt"`
}

type DownloadSafeReq struct {
	Index *IndexNode `protobuf:"bytes,1,opt"`
	_     [0]func()
}

type UploadKeyRenewalReq struct {
	OldUKey proto.Option[string] `protobuf:"bytes,1,opt"`
	SubType proto.Option[uint32] `protobuf:"varint,2,opt"`
	_       [0]func()
}

type MsgInfoAuthReq struct {
	Msg      []byte               `protobuf:"bytes,1,opt"`
	AuthTime proto.Option[uint64] `protobuf:"varint,2,opt"`
}

type UploadCompletedReq struct {
	SrvSendMsg     proto.Option[bool]   `protobuf:"varint,1,opt"`
	ClientRandomId proto.Option[uint64] `protobuf:"varint,2,opt"`
	MsgInfo        *MsgInfo             `protobuf:"bytes,3,opt"`
	ClientSeq      proto.Option[uint32] `protobuf:"varint,4,opt"`
	_              [0]func()
}

type DeleteReq struct {
	Index         []*IndexNode         `protobuf:"bytes,1,rep"`
	NeedRecallMsg proto.Option[bool]   `protobuf:"varint,2,opt"`
	MsgSeq        proto.Option[uint64] `protobuf:"varint,3,opt"`
	MsgRandom     proto.Option[uint64] `protobuf:"varint,4,opt"`
	MsgTime       proto.Option[uint64] `protobuf:"varint,5,opt"`
}

type DownloadRKeyReq struct {
	Types []int32 `protobuf:"varint,1,rep"`
}

type UploadInfo struct {
	FileInfo    *FileInfo            `protobuf:"bytes,1,opt"`
	SubFileType proto.Option[uint32] `protobuf:"varint,2,opt"`
	_           [0]func()
}

type UploadReq struct {
	UploadInfo             []*UploadInfo        `protobuf:"bytes,1,rep"`
	TryFastUploadCompleted proto.Option[bool]   `protobuf:"varint,2,opt"`
	SrvSendMsg             proto.Option[bool]   `protobuf:"varint,3,opt"`
	ClientRandomId         proto.Option[uint64] `protobuf:"varint,4,opt"`
	CompatQMsgSceneType    proto.Option[uint32] `protobuf:"varint,5,opt"`
	ExtBizInfo             *ExtBizInfo          `protobuf:"bytes,6,opt"`
	ClientSeq              proto.Option[uint32] `protobuf:"varint,7,opt"`
	NoNeedCompatMsg        proto.Option[bool]   `protobuf:"varint,8,opt"`
}

type NTV2RichMediaResp struct {
	RespHead         *MultiMediaRespHead   `protobuf:"bytes,1,opt"`
	Upload           *UploadResp           `protobuf:"bytes,2,opt"`
	Download         *DownloadResp         `protobuf:"bytes,3,opt"`
	DownloadRKey     *DownloadRKeyResp     `protobuf:"bytes,4,opt"`
	Delete           *DeleteResp           `protobuf:"bytes,5,opt"`
	UploadCompleted  *UploadCompletedResp  `protobuf:"bytes,6,opt"`
	MsgInfoAuth      *MsgInfoAuthResp      `protobuf:"bytes,7,opt"`
	UploadKeyRenewal *UploadKeyRenewalResp `protobuf:"bytes,8,opt"`
	DownloadSafe     *DownloadSafeResp     `protobuf:"bytes,9,opt"`
	Extension        []byte                `protobuf:"bytes,99,opt"`
}

type MultiMediaRespHead struct {
	Common  *CommonHead          `protobuf:"bytes,1,opt"`
	RetCode proto.Option[uint32] `protobuf:"varint,2,opt"`
	Message proto.Option[string] `protobuf:"bytes,3,opt"`
	_       [0]func()
}

type DownloadResp struct {
	RKeyParam      proto.Option[string] `protobuf:"bytes,1,opt"`
	RKeyTtlSecond  proto.Option[uint32] `protobuf:"varint,2,opt"`
	Info           *DownloadInfo        `protobuf:"bytes,3,opt"`
	RKeyCreateTime proto.Option[uint32] `protobuf:"varint,4,opt"`
	_              [0]func()
}

type DownloadInfo struct {
	Domain        proto.Option[string] `protobuf:"bytes,1,opt"`
	UrlPath       proto.Option[string] `protobuf:"bytes,2,opt"`
	HttpsPort     proto.Option[uint32] `protobuf:"varint,3,opt"`
	IPv4S         []*IPv4              `protobuf:"bytes,4,rep"`
	IPv6S         []*IPv6              `protobuf:"bytes,5,rep"`
	PicUrlExtInfo *PicUrlExtInfo       `protobuf:"bytes,6,opt"`
	VideoExtInfo  *VideoExtInfo        `protobuf:"bytes,7,opt"`
}

type IPv4 struct {
	OutIp   proto.Option[uint32] `protobuf:"varint,1,opt"`
	OutPort proto.Option[uint32] `protobuf:"varint,2,opt"`
	InIp    proto.Option[uint32] `protobuf:"varint,3,opt"`
	InPort  proto.Option[uint32] `protobuf:"varint,4,opt"`
	IpType  proto.Option[uint32] `protobuf:"varint,5,opt"`
	_       [0]func()
}

type IPv6 struct {
	OutIp   []byte               `protobuf:"bytes,1,opt"`
	OutPort proto.Option[uint32] `protobuf:"varint,2,opt"`
	InIp    []byte               `protobuf:"bytes,3,opt"`
	InPort  proto.Option[uint32] `protobuf:"varint,4,opt"`
	IpType  proto.Option[uint32] `protobuf:"varint,5,opt"`
}

type UploadResp struct {
	UKey          proto.Option[string]         `protobuf:"bytes,1,opt"`
	UKeyTtlSecond proto.Option[uint32]         `protobuf:"varint,2,opt"`
	IPv4S         []*IPv4                      `protobuf:"bytes,3,rep"`
	IPv6S         []*IPv6                      `protobuf:"bytes,4,rep"`
	MsgSeq        proto.Option[uint64]         `protobuf:"varint,5,opt"`
	MsgInfo       *MsgInfo                     `protobuf:"bytes,6,opt"`
	Ext           []*RichMediaStorageTransInfo `protobuf:"bytes,7,rep"`
	CompatQMsg    []byte                       `protobuf:"bytes,8,opt"`
	SubFileInfos  []*SubFileInfo               `protobuf:"bytes,10,rep"`
}

type RichMediaStorageTransInfo struct {
	SubType  proto.Option[uint32] `protobuf:"varint,1,opt"`
	ExtType  proto.Option[uint32] `protobuf:"varint,2,opt"`
	ExtValue []byte               `protobuf:"bytes,3,opt"`
}

type SubFileInfo struct {
	SubType       proto.Option[uint32] `protobuf:"varint,1,opt"`
	UKey          proto.Option[string] `protobuf:"bytes,2,opt"`
	UKeyTtlSecond proto.Option[uint32] `protobuf:"varint,3,opt"`
	IPv4S         []*IPv4              `protobuf:"bytes,4,rep"`
	IPv6S         []*IPv6              `protobuf:"bytes,5,rep"`
}

type DownloadSafeResp struct {
	_ [0]func()
}

type UploadKeyRenewalResp struct {
	Ukey       proto.Option[string] `protobuf:"bytes,1,opt"`
	UkeyTtlSec proto.Option[uint64] `protobuf:"varint,2,opt"`
	_          [0]func()
}

type MsgInfoAuthResp struct {
	AuthCode   proto.Option[uint32] `protobuf:"varint,1,opt"`
	Msg        []byte               `protobuf:"bytes,2,opt"`
	ResultTime proto.Option[uint64] `protobuf:"varint,3,opt"`
}

type UploadCompletedResp struct {
	MsgSeq proto.Option[uint64] `protobuf:"varint,1,opt"`
	_      [0]func()
}

type DeleteResp struct {
	_ [0]func()
}

type DownloadRKeyResp struct {
	RKeys []*RKeyInfo `protobuf:"bytes,1,rep"`
}

type RKeyInfo struct {
	Rkey           proto.Option[string] `protobuf:"bytes,1,opt"`
	RkeyTtlSec     proto.Option[uint64] `protobuf:"varint,2,opt"`
	StoreId        proto.Option[uint32] `protobuf:"varint,3,opt"`
	RkeyCreateTime proto.Option[uint32] `protobuf:"varint,4,opt"`
	Type           proto.Option[uint32] `protobuf:"varint,5,opt"`
	_              [0]func()
}
