// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/oidb/oidb_0x102a.proto

package oidb

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type D102AReqBody struct {
	Domain []string `protobuf:"bytes,1,rep"`
}

type D102ARspBody struct {
	PsKeys     map[string]string    `protobuf:"bytes,1,rep" protobuf_key:"bytes,1,opt" protobuf_val:"bytes,2,opt"`
	KeyType    proto.Option[int32]  `protobuf:"varint,2,opt"`
	ClientKey  proto.Option[string] `protobuf:"bytes,3,opt"`
	Expiration proto.Option[uint32] `protobuf:"varint,4,opt"`
}
