// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/oidb/oidb_0x8fc.proto

package oidb

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type CardType = int32

const (
	CardType_Text CardType = 1
	CardType_XC   CardType = 2
)

type D8FCReqBody struct {
	GroupCode      proto.Option[int64]  `protobuf:"varint,1,opt"`
	ShowFlag       proto.Option[uint32] `protobuf:"varint,2,opt"`
	MemLevelInfo   []*MemberInfo        `protobuf:"bytes,3,rep"`
	LevelNames     []*LevelName         `protobuf:"bytes,4,rep"`
	UpdateTime     proto.Option[uint32] `protobuf:"varint,5,opt"`
	OfficeMode     proto.Option[uint32] `protobuf:"varint,6,opt"`
	GroupOpenAppid proto.Option[uint32] `protobuf:"varint,7,opt"`
	Client         *ClientInfo          `protobuf:"bytes,8,opt"`
	AuthKey        []byte               `protobuf:"bytes,9,opt"`
}

type D8FCRspBody struct {
	GroupCode proto.Option[int64]  `protobuf:"varint,1,opt"`
	ErrInfo   proto.Option[string] `protobuf:"bytes,2,opt"`
	_         [0]func()
}

type CardNameElem struct {
	Type  proto.Option[CardType] `protobuf:"varint,1,opt"`
	Value []byte                 `protobuf:"bytes,2,opt"`
}

type ClientInfo struct {
	Implat    proto.Option[uint32] `protobuf:"varint,1,opt"`
	ClientVer proto.Option[string] `protobuf:"bytes,2,opt"`
	_         [0]func()
}

type LevelName struct {
	Level proto.Option[uint32] `protobuf:"varint,1,opt"`
	Name  proto.Option[string] `protobuf:"bytes,2,opt"`
	_     [0]func()
}

type MemberInfo struct {
	Uid                    proto.Option[string] `protobuf:"bytes,1,opt"`
	Point                  proto.Option[uint32] `protobuf:"varint,2,opt"`
	ActiveKey              proto.Option[uint32] `protobuf:"varint,3,opt"`
	Level                  proto.Option[uint32] `protobuf:"varint,4,opt"`
	SpecialTitle           []byte               `protobuf:"bytes,5,opt"`
	SpecialTitleExpireTime proto.Option[uint32] `protobuf:"varint,6,opt"`
	UinName                []byte               `protobuf:"bytes,7,opt"`
	MemberCardName         []byte               `protobuf:"bytes,8,opt"`
	Phone                  []byte               `protobuf:"bytes,9,opt"`
	Email                  []byte               `protobuf:"bytes,10,opt"`
	Remark                 []byte               `protobuf:"bytes,11,opt"`
	Gender                 proto.Option[uint32] `protobuf:"varint,12,opt"`
	Job                    []byte               `protobuf:"bytes,13,opt"`
	TribeLevel             proto.Option[uint32] `protobuf:"varint,14,opt"`
	TribePoint             proto.Option[uint32] `protobuf:"varint,15,opt"`
	RichCardName           []*CardNameElem      `protobuf:"bytes,16,rep"`
	CommRichCardName       []byte               `protobuf:"bytes,17,opt"`
}
