// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/oidb/oidb_0xed3.proto

package oidb

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type DED3ReqBody struct {
	ToUin     proto.Option[int64]  `protobuf:"varint,1,opt"`
	GroupCode proto.Option[int64]  `protobuf:"varint,2,opt"`
	MsgSeq    proto.Option[uint32] `protobuf:"varint,3,opt"`
	MsgRand   proto.Option[uint32] `protobuf:"varint,4,opt"`
	AioUin    proto.Option[int64]  `protobuf:"varint,5,opt"`
	NudgeType proto.Option[uint32] `protobuf:"varint,6,opt"`
	_         [0]func()
}

type DED3RspBody struct {
	_ [0]func()
}
