// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/oidb/oidb.proto

package oidb

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type Oidb struct {
	Command  proto.Option[uint32] `protobuf:"varint,1,opt"`
	Service  proto.Option[uint32] `protobuf:"varint,2,opt"`
	Result   proto.Option[uint32] `protobuf:"varint,3,opt"`
	Body     []byte               `protobuf:"bytes,4,opt"`
	Message  proto.Option[string] `protobuf:"bytes,5,opt"`
	Reserved proto.Option[uint32] `protobuf:"varint,12,opt"`
}
