// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/oidb/oidb_0x1097.proto

package oidb

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type D1097ReqBody struct {
	GroupCode proto.Option[int64] `protobuf:"varint,1,opt"`
	_         [0]func()
}

type D1097RspBody struct {
	_ [0]func()
}
