// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/oidb/oidb_0x89a.proto

package oidb

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type D89AReqBody struct {
	GroupCode           proto.Option[int64]   `protobuf:"varint,1,opt"`
	Group               *D89AReqBodyGroupInfo `protobuf:"bytes,2,opt"`
	OriginalOperatorUin proto.Option[int64]   `protobuf:"varint,3,opt"`
	ReqGroupOpenAppid   proto.Option[uint32]  `protobuf:"varint,4,opt"`
	_                   [0]func()
}

type D89ARspBody struct {
	GroupCode proto.Option[int64]  `protobuf:"varint,1,opt"`
	ErrorInfo proto.Option[string] `protobuf:"bytes,2,opt"`
	_         [0]func()
}

type D89AReqBodyGroupInfo struct {
	GroupExtAdmNum       proto.Option[uint32]    `protobuf:"varint,1,opt"`
	Flag                 proto.Option[uint32]    `protobuf:"varint,2,opt"`
	GroupName            proto.Option[string]    `protobuf:"bytes,3,opt"`
	GroupMemo            proto.Option[string]    `protobuf:"bytes,4,opt"`
	GroupFingerMemo      proto.Option[string]    `protobuf:"bytes,5,opt"`
	GroupAioSkinUrl      proto.Option[string]    `protobuf:"bytes,6,opt"`
	GroupBoardSkinUrl    proto.Option[string]    `protobuf:"bytes,7,opt"`
	GroupCoverSkinUrl    proto.Option[string]    `protobuf:"bytes,8,opt"`
	GroupGrade           proto.Option[uint32]    `protobuf:"varint,9,opt"`
	ActiveMemberNum      proto.Option[uint32]    `protobuf:"varint,10,opt"`
	CertificationType    proto.Option[uint32]    `protobuf:"varint,11,opt"`
	CertificationText    proto.Option[string]    `protobuf:"bytes,12,opt"`
	GroupRichFingerMemo  proto.Option[string]    `protobuf:"bytes,13,opt"`
	GroupNewGuidelines   *GroupNewGuidelinesInfo `protobuf:"bytes,14,opt"`
	GroupFace            proto.Option[uint32]    `protobuf:"varint,15,opt"`
	AddOption            proto.Option[uint32]    `protobuf:"varint,16,opt"`
	ShutupTime           proto.Option[uint32]    `protobuf:"varint,17,opt"`
	GroupTypeFlag        proto.Option[uint32]    `protobuf:"varint,18,opt"`
	GroupTag             []string                `protobuf:"bytes,19,rep"`
	GroupGeo             *GroupGeoInfo           `protobuf:"bytes,20,opt"`
	GroupClassExt        proto.Option[uint32]    `protobuf:"varint,21,opt"`
	GroupClassText       proto.Option[string]    `protobuf:"bytes,22,opt"`
	AppPrivilegeFlag     proto.Option[uint32]    `protobuf:"varint,23,opt"`
	AppPrivilegeMask     proto.Option[uint32]    `protobuf:"varint,24,opt"`
	GroupExInfo          *GroupExInfoOnly        `protobuf:"bytes,25,opt"`
	GroupSecLevel        proto.Option[uint32]    `protobuf:"varint,26,opt"`
	GroupSecLevelInfo    proto.Option[uint32]    `protobuf:"varint,27,opt"`
	SubscriptionUin      proto.Option[int64]     `protobuf:"varint,28,opt"`
	AllowMemberInvite    proto.Option[uint32]    `protobuf:"varint,29,opt"`
	GroupQuestion        proto.Option[string]    `protobuf:"bytes,30,opt"`
	GroupAnswer          proto.Option[string]    `protobuf:"bytes,31,opt"`
	GroupFlagExt3        proto.Option[uint32]    `protobuf:"varint,32,opt"`
	GroupFlagExt3Mask    proto.Option[uint32]    `protobuf:"varint,33,opt"`
	GroupOpenAppid       proto.Option[uint32]    `protobuf:"varint,34,opt"`
	NoFingerOpenFlag     proto.Option[uint32]    `protobuf:"varint,35,opt"`
	NoCodeFingerOpenFlag proto.Option[uint32]    `protobuf:"varint,36,opt"`
	RootId               proto.Option[int64]     `protobuf:"varint,37,opt"`
	MsgLimitFrequency    proto.Option[uint32]    `protobuf:"varint,38,opt"`
	HlGuildAppid         proto.Option[uint32]    `protobuf:"varint,39,opt"`
	HlGuildSubType       proto.Option[uint32]    `protobuf:"varint,40,opt"`
	HlGuildOrgid         proto.Option[uint32]    `protobuf:"varint,41,opt"`
	GroupFlagExt4        proto.Option[uint32]    `protobuf:"varint,42,opt"`
	GroupFlagExt4Mask    proto.Option[uint32]    `protobuf:"varint,43,opt"`
}

type GroupExInfoOnly struct {
	TribeId          proto.Option[uint32] `protobuf:"varint,1,opt"`
	MoneyForAddGroup proto.Option[uint32] `protobuf:"varint,2,opt"`
	_                [0]func()
}

type GroupGeoInfo struct {
	CityId     proto.Option[uint32] `protobuf:"varint,1,opt"`
	Longitude  proto.Option[uint64] `protobuf:"varint,2,opt"`
	Latitude   proto.Option[uint64] `protobuf:"varint,3,opt"`
	GeoContent proto.Option[string] `protobuf:"bytes,4,opt"`
	PoiId      proto.Option[uint64] `protobuf:"varint,5,opt"`
	_          [0]func()
}

type GroupNewGuidelinesInfo struct {
	Enabled proto.Option[bool]   `protobuf:"varint,1,opt"`
	Content proto.Option[string] `protobuf:"bytes,2,opt"`
	_       [0]func()
}
