// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/oidb/old_code_oidb_0xeac.proto

package oidb

// RemoveEssenceMessage
type OidbSvcTrpcTcp0XEAC struct {
	GroupUin uint64 `protobuf:"varint,1,opt"`
	Sequence uint64 `protobuf:"varint,2,opt"`
	Random   uint64 `protobuf:"varint,3,opt"`
	_        [0]func()
}
