// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/oidb/old_code_oidb_0xb5d_44.proto

package oidb

// Set Friend Request
type OidbSvcTrpcTcp0XB5D_44 struct {
	Accept    uint32 `protobuf:"varint,1,opt"` // 3 for accept, 5 for reject
	TargetUid string `protobuf:"bytes,2,opt"`
	_         [0]func()
}
