// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/oidb/old_code_oidb_0x8a0_1.proto

package oidb

import (
	proto "github.com/RomiChan/protobuf/proto"
)

// Group Kick Member
type OidbSvcTrpcTcp0X8A0_1 struct {
	GroupUin         uint64 `protobuf:"varint,1,opt"`
	TargetUid        string `protobuf:"bytes,3,opt"`
	RejectAddRequest bool   `protobuf:"varint,4,opt"` //string field5 = 5;
	_                [0]func()
}

type OidbSvcTrpcTcp0X8A0_1Response struct {
	GroupUin uint64               `protobuf:"varint,1,opt"`
	ErrorMsg proto.Option[string] `protobuf:"bytes,2,opt"`
	_        [0]func()
}
