// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: notify/notify.proto

package notify

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type Event0X20D struct {
	SubType proto.Option[uint64] `protobuf:"varint,1,opt"`
	Body    []byte               `protobuf:"bytes,2,opt"`
}

type FriendRecall struct {
	Info *FriendRecallInfo `protobuf:"bytes,1,opt"`
	_    [0]func()
}

type FriendRecallInfo struct {
	FromUid  proto.Option[string] `protobuf:"bytes,1,opt"`
	ToUid    proto.Option[string] `protobuf:"bytes,2,opt"`
	TipInfo  *FriendRecallTipInfo `protobuf:"bytes,13,opt"`
	Sequence proto.Option[int64]  `protobuf:"varint,20,opt"`
	_        [0]func()
}

type FriendRecallTipInfo struct {
	Tip proto.Option[string] `protobuf:"bytes,2,opt"`
	_   [0]func()
}

type FriendRequest struct {
	Info *FriendRequestInfo `protobuf:"bytes,1,opt"`
	_    [0]func()
}

type FriendRequestInfo struct {
	TargetUid proto.Option[string] `protobuf:"bytes,1,opt"`
	SourceUid proto.Option[string] `protobuf:"bytes,2,opt"`
	NewSource proto.Option[string] `protobuf:"bytes,5,opt"`
	Message   proto.Option[string] `protobuf:"bytes,10,opt"`
	Source    proto.Option[string] `protobuf:"bytes,11,opt"`
	_         [0]func()
}

type GroupChange struct {
	GroupUin  proto.Option[uint32] `protobuf:"varint,1,opt"`
	Flag      proto.Option[uint32] `protobuf:"varint,2,opt"`
	MemberUid proto.Option[string] `protobuf:"bytes,3,opt"`
	Type      proto.Option[uint32] `protobuf:"varint,4,opt"`
	Operator  []byte               `protobuf:"bytes,5,opt"`
	Field6    proto.Option[uint32] `protobuf:"varint,6,opt"`
	Field7    []byte               `protobuf:"bytes,7,opt"`
}

type OperatorInfo struct {
	Operator *OperatorField1 `protobuf:"bytes,1,opt"`
	_        [0]func()
}

type OperatorField1 struct {
	Uid    proto.Option[string] `protobuf:"bytes,1,opt"`
	Field2 proto.Option[uint32] `protobuf:"varint,2,opt"`
	Field3 []byte               `protobuf:"bytes,3,opt"`
	Field4 proto.Option[uint32] `protobuf:"varint,4,opt"`
	Field5 []byte               `protobuf:"bytes,5,opt"`
}

type EssenceMessage struct {
	GroupUin         proto.Option[int64]  `protobuf:"varint,1,opt"`
	MsgSequence      proto.Option[uint64] `protobuf:"varint,2,opt"`
	Random           proto.Option[uint32] `protobuf:"varint,3,opt"`
	SetFlag          proto.Option[uint32] `protobuf:"varint,4,opt"`
	MemberUin        proto.Option[uint32] `protobuf:"varint,5,opt"`
	OperatorUin      proto.Option[uint32] `protobuf:"varint,6,opt"`
	TimeStamp        proto.Option[uint32] `protobuf:"varint,7,opt"`
	MsgSequence2     proto.Option[uint64] `protobuf:"varint,8,opt"`
	OperatorNickName proto.Option[string] `protobuf:"bytes,9,opt"`
	MemberNickName   proto.Option[string] `protobuf:"bytes,10,opt"`
	SetFlag2         proto.Option[uint32] `protobuf:"varint,11,opt"`
	_                [0]func()
}

type GroupInvite struct {
	Body *GroupInviteBody `protobuf:"bytes,1,opt"`
	_    [0]func()
}

type GroupInviteBody struct {
	GroupUin   proto.Option[int64]  `protobuf:"varint,1,opt"`
	TargetUid  proto.Option[string] `protobuf:"bytes,5,opt"`
	InviterUid proto.Option[string] `protobuf:"bytes,6,opt"`
	_          [0]func()
}

type GroupJoin struct {
	GroupUin  proto.Option[int64]  `protobuf:"varint,1,opt"`
	Type      proto.Option[uint64] `protobuf:"varint,2,opt"`
	TargetUid proto.Option[string] `protobuf:"bytes,3,opt"`
	Comment   proto.Option[string] `protobuf:"bytes,5,opt"`
	_         [0]func()
}

type GroupReactionData0 struct {
	Data *GroupReactionData1 `protobuf:"bytes,1,opt"`
	_    [0]func()
}

type GroupReactionData1 struct {
	Data *GroupReactionData2 `protobuf:"bytes,1,opt"`
	_    [0]func()
}

type GroupReactionData2 struct {
	Target *GroupReactionTarget `protobuf:"bytes,2,opt"`
	Data   *GroupReactionData3  `protobuf:"bytes,3,opt"`
	_      [0]func()
}

type GroupReactionTarget struct {
	Sequence proto.Option[uint64] `protobuf:"varint,1,opt"`
	_        [0]func()
}

type GroupReactionData3 struct {
	Code         proto.Option[string] `protobuf:"bytes,1,opt"`
	CurrentCount proto.Option[uint32] `protobuf:"varint,3,opt"`
	OperatorUid  proto.Option[string] `protobuf:"bytes,4,opt"`
	Type         proto.Option[uint32] `protobuf:"varint,5,opt"`
	_            [0]func()
}

type GroupRecall struct {
	OperatorUid    proto.Option[string] `protobuf:"bytes,1,opt"`
	RecallMessages []*RecallMessage     `protobuf:"bytes,3,rep"`
	UserDef        []byte               `protobuf:"bytes,5,opt"`
	GroupType      proto.Option[int32]  `protobuf:"varint,6,opt"`
	OpType         proto.Option[int32]  `protobuf:"varint,7,opt"`
	TipInfo        *GroupRecallTipInfo  `protobuf:"bytes,9,opt"`
}

type RecallMessage struct {
	Sequence  proto.Option[uint64] `protobuf:"varint,1,opt"`
	Time      proto.Option[uint32] `protobuf:"varint,2,opt"`
	Random    proto.Option[uint32] `protobuf:"varint,3,opt"`
	Type      proto.Option[uint32] `protobuf:"varint,4,opt"`
	Flag      proto.Option[uint32] `protobuf:"varint,5,opt"`
	AuthorUid proto.Option[string] `protobuf:"bytes,6,opt"`
	_         [0]func()
}

type GroupRecallTipInfo struct {
	Tip proto.Option[string] `protobuf:"bytes,2,opt"`
	_   [0]func()
}

type GroupRecallNudge struct {
	OperatorUid proto.Option[string] `protobuf:"bytes,1,opt"`
	GroupUin    proto.Option[int64]  `protobuf:"varint,3,opt"`
	BusiId      proto.Option[uint64] `protobuf:"varint,4,opt"`
	TipsSeqId   proto.Option[uint64] `protobuf:"varint,5,opt"`
	_           [0]func()
}

type NotifyMessageBody struct {
	NotifyType       proto.Option[uint32] `protobuf:"varint,1,opt"`
	GroupUin         proto.Option[int64]  `protobuf:"varint,4,opt"`
	EventParam       []byte               `protobuf:"bytes,5,opt"`
	Recall           *GroupRecall         `protobuf:"bytes,11,opt"`
	SubType          proto.Option[uint32] `protobuf:"varint,13,opt"`
	OperatorUid      proto.Option[string] `protobuf:"bytes,21,opt"`
	GeneralGrayTip   *GeneralGrayTipInfo  `protobuf:"bytes,26,opt"`
	MsgSequence      proto.Option[uint64] `protobuf:"varint,37,opt"`
	Field39          proto.Option[uint32] `protobuf:"varint,39,opt"`
	GroupRecallNudge *GroupRecallNudge    `protobuf:"bytes,40,opt"`
	Reaction         *GroupReactionData0  `protobuf:"bytes,44,opt"`
	TipsSeqId        proto.Option[uint64] `protobuf:"varint,50,opt"`
	EssenceMessage   *EssenceMessage      `protobuf:"bytes,33,opt"`
}

type GeneralGrayTipInfo struct {
	BusiType      proto.Option[uint64] `protobuf:"varint,1,opt"`
	BusiId        proto.Option[uint64] `protobuf:"varint,2,opt"`
	CtrlFlag      proto.Option[uint32] `protobuf:"varint,3,opt"`
	C2CType       proto.Option[uint32] `protobuf:"varint,4,opt"`
	ServiceType   proto.Option[uint32] `protobuf:"varint,5,opt"`
	TemplId       proto.Option[uint64] `protobuf:"varint,6,opt"`
	MsgTemplParam []*TemplParam        `protobuf:"bytes,7,rep"`
	Content       proto.Option[string] `protobuf:"bytes,8,opt"`
	TipsSeqId     proto.Option[uint64] `protobuf:"varint,10,opt"`
	MsgInfo       *GrayTipMsgInfo      `protobuf:"bytes,100,opt"`
}

type GrayTipMsgInfo struct {
	Sequence proto.Option[uint64] `protobuf:"varint,6,opt"`
	_        [0]func()
}

type TemplParam struct {
	Name  proto.Option[string] `protobuf:"bytes,1,opt"`
	Value proto.Option[string] `protobuf:"bytes,2,opt"`
	_     [0]func()
}

type FriendRecallPokeInfo struct {
	SelfUid     proto.Option[string] `protobuf:"bytes,1,opt"`
	PeerUid     proto.Option[string] `protobuf:"bytes,2,opt"`
	OperatorUid proto.Option[string] `protobuf:"bytes,3,opt"`
	BusiId      proto.Option[uint64] `protobuf:"varint,4,opt"`
	TipsSeqId   proto.Option[uint64] `protobuf:"varint,5,opt"`
	_           [0]func()
}
