// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: notify/old_code_notify.proto

package notify

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type NewFriend struct {
	Field1 uint32         `protobuf:"varint,1,opt"`
	Info   *NewFriendInfo `protobuf:"bytes,2,opt"`
	_      [0]func()
}

type NewFriendInfo struct {
	Uid      string `protobuf:"bytes,1,opt"`
	Field2   uint32 `protobuf:"varint,2,opt"`
	Time     uint32 `protobuf:"fixed32,3,opt"`
	Message  string `protobuf:"bytes,4,opt"`
	NickName string `protobuf:"bytes,5,opt"`
	Field6   uint32 `protobuf:"varint,6,opt"`
	Field7   uint32 `protobuf:"varint,7,opt"`
	ToUid    string `protobuf:"bytes,9,opt"`
	_        [0]func()
}

type GroupAdmin struct {
	GroupUin  uint32          `protobuf:"varint,1,opt"`
	Flag      uint32          `protobuf:"varint,2,opt"`
	IsPromote bool            `protobuf:"varint,3,opt"`
	Body      *GroupAdminBody `protobuf:"bytes,4,opt"`
	_         [0]func()
}

type GroupAdminBody struct {
	ExtraDisable *GroupAdminExtra `protobuf:"bytes,1,opt"`
	ExtraEnable  *GroupAdminExtra `protobuf:"bytes,2,opt"`
	_            [0]func()
}

type GroupAdminExtra struct {
	AdminUid  string `protobuf:"bytes,1,opt"`
	IsPromote bool   `protobuf:"varint,2,opt"`
	_         [0]func()
}

type GroupInvitation struct {
	Cmd  int32           `protobuf:"varint,1,opt"`
	Info *InvitationInfo `protobuf:"bytes,2,opt"`
	_    [0]func()
}

type InvitationInfo struct {
	Inner *InvitationInner `protobuf:"bytes,1,opt"`
	_     [0]func()
}

type InvitationInner struct {
	GroupUin   uint32 `protobuf:"varint,1,opt"`
	Field2     uint32 `protobuf:"varint,2,opt"`
	Field3     uint32 `protobuf:"varint,3,opt"`
	Field4     uint32 `protobuf:"varint,4,opt"`
	TargetUid  string `protobuf:"bytes,5,opt"`
	InvitorUid string `protobuf:"bytes,6,opt"`
	Field7     uint32 `protobuf:"varint,7,opt"`
	Field9     uint32 `protobuf:"varint,9,opt"`
	Field10    []byte `protobuf:"bytes,10,opt"`
	Field11    uint32 `protobuf:"varint,11,opt"`
	Field12    string `protobuf:"bytes,12,opt"`
}

type GroupMute struct {
	GroupUin    uint32               `protobuf:"varint,1,opt"`
	SubType     uint32               `protobuf:"varint,2,opt"`
	Field3      uint32               `protobuf:"varint,3,opt"`
	OperatorUid proto.Option[string] `protobuf:"bytes,4,opt"`
	Data        *GroupMuteData       `protobuf:"bytes,5,opt"`
	_           [0]func()
}

type GroupMuteData struct {
	Timestamp uint32          `protobuf:"varint,1,opt"`
	Type      uint32          `protobuf:"varint,2,opt"`
	State     *GroupMuteState `protobuf:"bytes,3,opt"`
	_         [0]func()
}

type GroupMuteState struct {
	TargetUid proto.Option[string] `protobuf:"bytes,1,opt"`
	Duration  uint32               `protobuf:"varint,2,opt"` // uint.MaxValue = Mute else Lift
	_         [0]func()
}

type GroupSpecialTitle struct {
	Content   string `protobuf:"bytes,2,opt"`
	Field3    uint32 `protobuf:"varint,3,opt"`
	TargetUin uint32 `protobuf:"varint,5,opt"`
	_         [0]func()
}

type SelfRenameMsg struct {
	Field1 uint32          `protobuf:"varint,1,opt"` // 20
	Body   *SelfRenameBody `protobuf:"bytes,20,opt"`
	_      [0]func()
}

type SelfRenameBody struct {
	Uin        uint32      `protobuf:"varint,1,opt"`
	RenameData *RenameData `protobuf:"bytes,2,opt"`
	_          [0]func()
}

type FriendRenameMsg struct {
	Body *FriendRenameMsgBody `protobuf:"bytes,1,opt"`
	_    [0]func()
}

type FriendRenameMsgBody struct {
	Field2 uint32               `protobuf:"varint,2,opt"` // 20
	Data   *FriendRenameMsgData `protobuf:"bytes,8,opt"`
	_      [0]func()
}

type FriendRenameMsgData struct {
	Uid        string      `protobuf:"bytes,1,opt"`
	RenameData *RenameData `protobuf:"bytes,2,opt"`
	_          [0]func()
}

type RenameData struct {
	Field1   uint32 `protobuf:"varint,1,opt"` // 20002
	NickName string `protobuf:"bytes,2,opt"`
	_        [0]func()
}
