// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: notify/old_code_notify_body.proto

package notify

// ref https://github.com/mamoe/mirai/blob/283f8840d4682cc30fbdd87c66fe76f6a71ff8db/mirai-core/src/commonMain/kotlin/network/protocol/data/proto/Cmd0x857.kt#L76
type AIOGrayTipsInfo struct {
	ShowLatest     uint32 `protobuf:"varint,1,opt"`
	Content        string `protobuf:"bytes,2,opt"`
	Remind         uint32 `protobuf:"varint,3,opt"`
	Brief          []byte `protobuf:"bytes,4,opt"`
	ReceiverUin    uint64 `protobuf:"varint,5,opt"`
	ReliaoAdminOpt uint32 `protobuf:"varint,6,opt"`
	RobotGroupOpt  uint32 `protobuf:"varint,7,opt"`
}

// ref https://github.com/mamoe/mirai/blob/283f8840d4682cc30fbdd87c66fe76f6a71ff8db/mirai-core/src/commonMain/kotlin/network/protocol/data/proto/Cmd0x857.kt#L370
type RedGrayTipsInfo struct {
	ShowLatest          uint32 `protobuf:"varint,1,opt"`
	SenderUin           uint64 `protobuf:"varint,2,opt"`
	ReceiverUin         uint64 `protobuf:"varint,3,opt"`
	SenderRichContent   string `protobuf:"bytes,4,opt"`
	ReceiverRichContent string `protobuf:"bytes,5,opt"`
	AuthKey             []byte `protobuf:"bytes,6,opt"`
	MsgType             int32  `protobuf:"zigzag32,7,opt"`
	LuckyFlag           uint32 `protobuf:"varint,8,opt"`
	HideFlag            uint32 `protobuf:"varint,9,opt"`
	LuckyUin            uint64 `protobuf:"varint,12,opt"`
}
