// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/operation/fetch_stranger.proto

package operation

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type FetchStrangerByUidRequest struct {
	Uid  proto.Option[string]       `protobuf:"bytes,1,opt"`
	Keys []*FetchStrangerRequestKey `protobuf:"bytes,3,rep"`
}

type FetchStrangerByUinRequest struct {
	Uin  proto.Option[int64]        `protobuf:"varint,1,opt"`
	Keys []*FetchStrangerRequestKey `protobuf:"bytes,3,rep"`
}

type FetchStrangerRequestKey struct {
	Key proto.Option[uint64] `protobuf:"varint,1,opt"`
	_   [0]func()
}

type FetchStrangerResponse struct {
	Body *FetchStrangerResponseBody `protobuf:"bytes,1,opt"`
	_    [0]func()
}

type FetchStrangerResponseBody struct {
	Properties *FetchStrangerResponseProperties `protobuf:"bytes,2,opt"`
	Uin        proto.Option[uint32]             `protobuf:"varint,3,opt"`
	_          [0]func()
}

type FetchStrangerResponseProperties struct {
	NumberProperties []*FetchStrangerResponseNumberProperties `protobuf:"bytes,1,rep"`
	BytesProperties  []*FetchStrangerResponseBytesProperties  `protobuf:"bytes,2,rep"`
}

type FetchStrangerResponseNumberProperties struct {
	Key   proto.Option[uint64] `protobuf:"varint,1,opt"`
	Value proto.Option[uint64] `protobuf:"varint,2,opt"`
	_     [0]func()
}

type FetchStrangerResponseBytesProperties struct {
	Key   proto.Option[uint64] `protobuf:"varint,1,opt"`
	Value []byte               `protobuf:"bytes,2,opt"`
}
