// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/operation/fetch_group_extra.proto

package operation

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type FetchGroupExtraRequest struct {
	Random proto.Option[int64]           `protobuf:"varint,1,opt"`
	Config *FetchGroupExtraRequestConfig `protobuf:"bytes,2,opt"`
	_      [0]func()
}

type FetchGroupExtraRequestConfig struct {
	GroupUin proto.Option[int64]                `protobuf:"varint,1,opt"`
	Flags    *FetchGroupExtraRequestConfigFlags `protobuf:"bytes,2,opt"`
	_        [0]func()
}

type FetchGroupExtraResponse struct {
	Info *FetchGroupExtraResponseInfo `protobuf:"bytes,1,opt"`
	_    [0]func()
}

type FetchGroupExtraResponseInfo struct {
	GroupUin proto.Option[int64]                `protobuf:"varint,1,opt"`
	Result   *FetchGroupExtraResponseInfoResult `protobuf:"bytes,3,opt"`
	_        [0]func()
}
