// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/operation/fetch_group_notifications.proto

package operation

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type FetchGroupNotificationsRequest struct {
	Count         proto.Option[uint64] `protobuf:"varint,1,opt"`
	StartSequence proto.Option[uint64] `protobuf:"varint,2,opt"`
	_             [0]func()
}

type FetchGroupNotificationsResponse struct {
	GroupNotifications []*FetchGroupNotificationsResponseNotification `protobuf:"bytes,1,rep"`
}

type FetchGroupNotificationsResponseNotification struct {
	Sequence proto.Option[uint64]                              `protobuf:"varint,1,opt"`
	Type     proto.Option[uint64]                              `protobuf:"varint,2,opt"`
	State    proto.Option[uint64]                              `protobuf:"varint,3,opt"`
	Group    *FetchGroupNotificationsResponseNotificationGroup `protobuf:"bytes,4,opt"`
	Target   *FetchGroupNotificationsResponseNotificationUser  `protobuf:"bytes,5,opt"`
	Inviter  *FetchGroupNotificationsResponseNotificationUser  `protobuf:"bytes,6,opt"`
	Operator *FetchGroupNotificationsResponseNotificationUser  `protobuf:"bytes,7,opt"`
	Comment  proto.Option[string]                              `protobuf:"bytes,10,opt"`
	_        [0]func()
}

type FetchGroupNotificationsResponseNotificationGroup struct {
	GroupUin proto.Option[int64] `protobuf:"varint,1,opt"`
	_        [0]func()
}

type FetchGroupNotificationsResponseNotificationUser struct {
	Uid proto.Option[string] `protobuf:"bytes,1,opt"`
	_   [0]func()
}
