// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/operation/fetch_groups.proto

package operation

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type FetchGroupsRequest struct {
	Config *FetchGroupsRequestConfig `protobuf:"bytes,1,opt"`
	_      [0]func()
}

type FetchGroupsRequestConfig struct {
	Config1 *FetchGroupsRequestConfig1 `protobuf:"bytes,1,opt"`
	Config2 *FetchGroupsRequestConfig2 `protobuf:"bytes,2,opt"`
	Config3 *FetchGroupsRequestConfig3 `protobuf:"bytes,3,opt"`
	_       [0]func()
}

type FetchGroupsRequestConfig1 struct {
	GroupOwner  proto.Option[bool] `protobuf:"varint,1,opt"`
	Field2      proto.Option[bool] `protobuf:"varint,2,opt"`
	MemberMax   proto.Option[bool] `protobuf:"varint,3,opt"`
	MemberCount proto.Option[bool] `protobuf:"varint,4,opt"`
	GroupName   proto.Option[bool] `protobuf:"varint,5,opt"`
	Field8      proto.Option[bool] `protobuf:"varint,8,opt"`
	Field9      proto.Option[bool] `protobuf:"varint,9,opt"`
	Field10     proto.Option[bool] `protobuf:"varint,10,opt"`
	Field11     proto.Option[bool] `protobuf:"varint,11,opt"`
	Field12     proto.Option[bool] `protobuf:"varint,12,opt"`
	Field13     proto.Option[bool] `protobuf:"varint,13,opt"`
	Field14     proto.Option[bool] `protobuf:"varint,14,opt"`
	Field15     proto.Option[bool] `protobuf:"varint,15,opt"`
	Field16     proto.Option[bool] `protobuf:"varint,16,opt"`
	Field17     proto.Option[bool] `protobuf:"varint,17,opt"`
	Field18     proto.Option[bool] `protobuf:"varint,18,opt"`
	Question    proto.Option[bool] `protobuf:"varint,19,opt"`
	Field20     proto.Option[bool] `protobuf:"varint,20,opt"`
	Field22     proto.Option[bool] `protobuf:"varint,22,opt"`
	Field23     proto.Option[bool] `protobuf:"varint,23,opt"`
	Field24     proto.Option[bool] `protobuf:"varint,24,opt"`
	Field25     proto.Option[bool] `protobuf:"varint,25,opt"`
	Field26     proto.Option[bool] `protobuf:"varint,26,opt"`
	Field27     proto.Option[bool] `protobuf:"varint,27,opt"`
	Field28     proto.Option[bool] `protobuf:"varint,28,opt"`
	Field29     proto.Option[bool] `protobuf:"varint,29,opt"`
	Field30     proto.Option[bool] `protobuf:"varint,30,opt"`
	Field31     proto.Option[bool] `protobuf:"varint,31,opt"`
	Field32     proto.Option[bool] `protobuf:"varint,32,opt"`
	Field5001   proto.Option[bool] `protobuf:"varint,5001,opt"`
	Field5002   proto.Option[bool] `protobuf:"varint,5002,opt"`
	Field5003   proto.Option[bool] `protobuf:"varint,5003,opt"`
	_           [0]func()
}

type FetchGroupsRequestConfig2 struct {
	Field1 proto.Option[bool] `protobuf:"varint,1,opt"`
	Field2 proto.Option[bool] `protobuf:"varint,2,opt"`
	Field3 proto.Option[bool] `protobuf:"varint,3,opt"`
	Field4 proto.Option[bool] `protobuf:"varint,4,opt"`
	Field5 proto.Option[bool] `protobuf:"varint,5,opt"`
	Field6 proto.Option[bool] `protobuf:"varint,6,opt"`
	Field7 proto.Option[bool] `protobuf:"varint,7,opt"`
	Field8 proto.Option[bool] `protobuf:"varint,8,opt"`
	_      [0]func()
}

type FetchGroupsRequestConfig3 struct {
	Field5 proto.Option[bool] `protobuf:"varint,5,opt"`
	Field6 proto.Option[bool] `protobuf:"varint,6,opt"`
	_      [0]func()
}

type FetchGroupsResponse struct {
	Groups []*FetchGroupsResponseGroup `protobuf:"bytes,2,rep"`
}

type FetchGroupsResponseGroup struct {
	GroupUin   proto.Option[int64]            `protobuf:"varint,3,opt"`
	Info       *FetchGroupsResponseGroupInfo  `protobuf:"bytes,4,opt"`
	CustomInfo *FetchGroupsResponseCustomInfo `protobuf:"bytes,5,opt"`
	_          [0]func()
}

type FetchGroupsResponseGroupInfo struct {
	GroupOwner   *FetchGroupsResponseMember `protobuf:"bytes,1,opt"`
	CreatedTime  proto.Option[uint32]       `protobuf:"varint,2,opt"`
	MemberMax    proto.Option[uint32]       `protobuf:"varint,3,opt"`
	MemberCount  proto.Option[uint32]       `protobuf:"varint,4,opt"`
	GroupName    proto.Option[string]       `protobuf:"bytes,5,opt"`
	Description  proto.Option[string]       `protobuf:"bytes,18,opt"`
	Question     proto.Option[string]       `protobuf:"bytes,19,opt"`
	Announcement proto.Option[string]       `protobuf:"bytes,30,opt"`
	_            [0]func()
}

type FetchGroupsResponseCustomInfo struct {
	LastSpeakTime proto.Option[int64]  `protobuf:"varint,1,opt"`
	LastestSeq    proto.Option[uint32] `protobuf:"varint,5,opt"`
	_             [0]func()
}

type FetchGroupsResponseMember struct {
	Remark proto.Option[string] `protobuf:"bytes,3,opt"`
	_      [0]func()
}
