// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/operation/fetch_group_members.proto

package operation

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type FetchGroupMembersRequest struct {
	GroupUin proto.Option[int64]           `protobuf:"varint,1,opt"`
	Field2   proto.Option[uint32]          `protobuf:"varint,2,opt"`
	Field3   proto.Option[uint32]          `protobuf:"varint,3,opt"`
	Body     *FetchGroupMembersRequestBody `protobuf:"bytes,4,opt"`
	Cookie   []byte                        `protobuf:"bytes,15,opt"`
}

type FetchGroupMembersRequestBody struct {
	MemberName       proto.Option[bool] `protobuf:"varint,10,opt"`
	MemberCard       proto.Option[bool] `protobuf:"varint,11,opt"`
	Level            proto.Option[bool] `protobuf:"varint,12,opt"`
	Field13          proto.Option[bool] `protobuf:"varint,13,opt"`
	Field16          proto.Option[bool] `protobuf:"varint,16,opt"`
	SpecialTitle     proto.Option[bool] `protobuf:"varint,17,opt"`
	Field18          proto.Option[bool] `protobuf:"varint,18,opt"`
	Field20          proto.Option[bool] `protobuf:"varint,20,opt"`
	Field21          proto.Option[bool] `protobuf:"varint,21,opt"`
	JoinTimestamp    proto.Option[bool] `protobuf:"varint,100,opt"`
	LastMsgTimestamp proto.Option[bool] `protobuf:"varint,101,opt"`
	ShutUpTimestamp  proto.Option[bool] `protobuf:"varint,102,opt"`
	Field103         proto.Option[bool] `protobuf:"varint,103,opt"`
	Field104         proto.Option[bool] `protobuf:"varint,104,opt"`
	Field105         proto.Option[bool] `protobuf:"varint,105,opt"`
	Field106         proto.Option[bool] `protobuf:"varint,106,opt"`
	Permission       proto.Option[bool] `protobuf:"varint,107,opt"`
	Field200         proto.Option[bool] `protobuf:"varint,200,opt"`
	Field201         proto.Option[bool] `protobuf:"varint,201,opt"`
	_                [0]func()
}

type FetchGroupMembersResponse struct {
	GroupUin            proto.Option[int64]                `protobuf:"varint,1,opt"`
	Members             []*FetchGroupMembersResponseMember `protobuf:"bytes,2,rep"`
	MemberCount         proto.Option[uint32]               `protobuf:"varint,3,opt"`
	MemberListChangeSeq proto.Option[uint32]               `protobuf:"varint,5,opt"`
	MemberCardSeq       proto.Option[uint32]               `protobuf:"varint,6,opt"`
	Cookie              []byte                             `protobuf:"bytes,15,opt"`
}

type FetchGroupMembersResponseMember struct {
	Id               *FetchGroupMembersResponseId    `protobuf:"bytes,1,opt"`
	MemberName       proto.Option[string]            `protobuf:"bytes,10,opt"`
	SpecialTitle     proto.Option[string]            `protobuf:"bytes,17,opt"`
	MemberCard       *FetchGroupMembersResponseCard  `protobuf:"bytes,11,opt"`
	Level            *FetchGroupMembersResponseLevel `protobuf:"bytes,12,opt"`
	JoinTimestamp    proto.Option[uint32]            `protobuf:"varint,100,opt"`
	LastMsgTimestamp proto.Option[uint32]            `protobuf:"varint,101,opt"`
	ShutUpTimestamp  proto.Option[uint32]            `protobuf:"varint,102,opt"`
	Permission       proto.Option[uint32]            `protobuf:"varint,107,opt"`
	_                [0]func()
}

type FetchGroupMembersResponseId struct {
	Uid proto.Option[string] `protobuf:"bytes,2,opt"`
	Uin proto.Option[uint32] `protobuf:"varint,4,opt"`
	_   [0]func()
}

type FetchGroupMembersResponseCard struct {
	MemberCard proto.Option[string] `protobuf:"bytes,2,opt"`
	_          [0]func()
}

type FetchGroupMembersResponseLevel struct {
	Infos []uint32             `protobuf:"varint,1,rep"`
	Level proto.Option[uint32] `protobuf:"varint,2,opt"`
}
