// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/operation/file_upload_ext.proto

package operation

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type FileUploadExt struct {
	Unknown1   proto.Option[int32] `protobuf:"varint,1,opt"`
	Unknown2   proto.Option[int32] `protobuf:"varint,2,opt"`
	Unknown3   proto.Option[int32] `protobuf:"varint,3,opt"`
	Entry      *FileUploadEntry    `protobuf:"bytes,100,opt"`
	Unknown200 proto.Option[int32] `protobuf:"varint,200,opt"`
	_          [0]func()
}

type FileUploadEntry struct {
	BusiBuff     *ExcitingBusiInfo     `protobuf:"bytes,100,opt"`
	FileEntry    *ExcitingFileEntry    `protobuf:"bytes,200,opt"`
	ClientInfo   *ExcitingClientInfo   `protobuf:"bytes,300,opt"`
	FileNameInfo *ExcitingFileNameInfo `protobuf:"bytes,400,opt"`
	Host         *ExcitingHostConfig   `protobuf:"bytes,500,opt"`
	_            [0]func()
}

type ExcitingBusiInfo struct {
	BusId       proto.Option[int32] `protobuf:"varint,1,opt"`
	SenderUin   proto.Option[int64] `protobuf:"varint,100,opt"`
	ReceiverUin proto.Option[int64] `protobuf:"varint,200,opt"`
	GroupCode   proto.Option[int64] `protobuf:"varint,400,opt"`
	_           [0]func()
}

type ExcitingFileEntry struct {
	FileSize  proto.Option[int64]  `protobuf:"varint,100,opt"`
	Md5       []byte               `protobuf:"bytes,200,opt"`
	CheckKey  []byte               `protobuf:"bytes,300,opt"`
	Md510M    []byte               `protobuf:"bytes,400,opt"`
	Sha3      []byte               `protobuf:"bytes,500,opt"`
	FileId    proto.Option[string] `protobuf:"bytes,600,opt"`
	UploadKey []byte               `protobuf:"bytes,700,opt"`
}

type ExcitingClientInfo struct {
	ClientType   proto.Option[int32]  `protobuf:"varint,100,opt"`
	AppId        proto.Option[string] `protobuf:"bytes,200,opt"`
	TerminalType proto.Option[int32]  `protobuf:"varint,300,opt"`
	ClientVer    proto.Option[string] `protobuf:"bytes,400,opt"`
	Unknown      proto.Option[int32]  `protobuf:"varint,600,opt"`
	_            [0]func()
}

type ExcitingFileNameInfo struct {
	FileName proto.Option[string] `protobuf:"bytes,100,opt"`
	_        [0]func()
}

type ExcitingHostConfig struct {
	Hosts []*ExcitingHostInfo `protobuf:"bytes,200,rep"`
}

type ExcitingHostInfo struct {
	Url  *ExcitingUrlInfo     `protobuf:"bytes,1,opt"`
	Port proto.Option[uint32] `protobuf:"varint,2,opt"`
	_    [0]func()
}

type ExcitingUrlInfo struct {
	Unknown proto.Option[int32]  `protobuf:"varint,1,opt"`
	Host    proto.Option[string] `protobuf:"bytes,2,opt"`
	_       [0]func()
}
