// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/operation/flash_transfer_upload.proto

package operation

type FlashTransferUploadReq struct {
	Field1 uint32                      `protobuf:"varint,1,opt"` // 0
	AppId  uint32                      `protobuf:"varint,2,opt"` // 1407
	Field3 uint32                      `protobuf:"varint,3,opt"` // 0
	Body   *FlashTransferUploadReqBody `protobuf:"bytes,107,opt"`
	_      [0]func()
}

type FlashTransferUploadReqBody struct {
	Field1     []byte                   `protobuf:"bytes,1,opt"` // empty
	UKey       string                   `protobuf:"bytes,2,opt"`
	Start      uint32                   `protobuf:"varint,3,opt"` // index
	End        uint32                   `protobuf:"varint,4,opt"` // start + size - 1
	Sha1       []byte                   `protobuf:"bytes,5,opt"`  // body_sha1
	Sha1StateV *FlashTransferSha1StateV `protobuf:"bytes,6,opt"`
	Body       []byte                   `protobuf:"bytes,7,opt"`
}

type FlashTransferSha1StateV struct {
	State [][]byte `protobuf:"bytes,1,rep"`
}

type FlashTransferUploadRsp struct {
	Status string `protobuf:"bytes,5,opt"`
	_      [0]func()
}
