// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/operation/flash_transfer_upload.proto

package operation

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type FlashTransferUploadReq struct {
	FieId1 proto.Option[uint32]     `protobuf:"varint,1,opt"`
	AppId  proto.Option[uint32]     `protobuf:"varint,2,opt"`
	FieId3 proto.Option[uint32]     `protobuf:"varint,3,opt"`
	Body   *FlashTransferUploadBody `protobuf:"bytes,107,opt"`
	_      [0]func()
}

type FlashTransferUploadBody struct {
	FieId1     []byte                   `protobuf:"bytes,1,opt"`
	UKey       proto.Option[string]     `protobuf:"bytes,2,opt"`
	Start      proto.Option[uint32]     `protobuf:"varint,3,opt"`
	End        proto.Option[uint32]     `protobuf:"varint,4,opt"`
	Sha1       []byte                   `protobuf:"bytes,5,opt"`
	Sha1StateV *FlashTransferSha1StateV `protobuf:"bytes,6,opt"`
	Body       []byte                   `protobuf:"bytes,7,opt"`
}

type FlashTransferSha1StateV struct {
	State [][]byte `protobuf:"bytes,1,rep"`
}

type FlashTransferUploadResp struct {
	Status proto.Option[string] `protobuf:"bytes,5,opt"`
	_      [0]func()
}
