// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/operation/offline_file_upload.proto

package operation

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type OfflineFileUploadRequest struct {
	Command                  proto.Option[uint32] `protobuf:"varint,1,opt"`
	Seq                      proto.Option[int32]  `protobuf:"varint,2,opt"`
	Upload                   *ApplyUploadReqV3    `protobuf:"bytes,19,opt"`
	BusinessId               proto.Option[int32]  `protobuf:"varint,101,opt"`
	ClientType               proto.Option[int32]  `protobuf:"varint,102,opt"`
	FlagSupportMediaPlatform proto.Option[int32]  `protobuf:"varint,200,opt"`
	_                        [0]func()
}

type ApplyUploadReqV3 struct {
	SenderUid      proto.Option[string] `protobuf:"bytes,10,opt"`
	ReceiverUid    proto.Option[string] `protobuf:"bytes,20,opt"`
	FileSize       proto.Option[uint32] `protobuf:"varint,30,opt"`
	FileName       proto.Option[string] `protobuf:"bytes,40,opt"`
	Md510MCheckSum []byte               `protobuf:"bytes,50,opt"`
	Sha1CheckSum   []byte               `protobuf:"bytes,60,opt"`
	LocalPath      proto.Option[string] `protobuf:"bytes,70,opt"`
	Md5CheckSum    []byte               `protobuf:"bytes,110,opt"`
	Sha3CheckSum   []byte               `protobuf:"bytes,120,opt"`
}

type OfflineFileUploadResponse struct {
	Command                  proto.Option[uint32] `protobuf:"varint,1,opt"`
	Seq                      proto.Option[int32]  `protobuf:"varint,2,opt"`
	Upload                   *ApplyUploadRespV3   `protobuf:"bytes,19,opt"`
	BusinessId               proto.Option[int32]  `protobuf:"varint,101,opt"`
	ClientType               proto.Option[int32]  `protobuf:"varint,102,opt"`
	FlagSupportMediaPlatform proto.Option[int32]  `protobuf:"varint,200,opt"`
	_                        [0]func()
}

type ApplyUploadRespV3 struct {
	RetCode                       proto.Option[int32]  `protobuf:"varint,10,opt"`
	RetMsg                        proto.Option[string] `protobuf:"bytes,20,opt"`
	TotalSpace                    proto.Option[int64]  `protobuf:"varint,30,opt"`
	UsedSpace                     proto.Option[int64]  `protobuf:"varint,40,opt"`
	UploadedSize                  proto.Option[int64]  `protobuf:"varint,50,opt"`
	UploadIp                      proto.Option[string] `protobuf:"bytes,60,opt"`
	UploadDomain                  proto.Option[string] `protobuf:"bytes,70,opt"`
	UploadPort                    proto.Option[uint32] `protobuf:"varint,80,opt"`
	Uuid                          proto.Option[string] `protobuf:"bytes,90,opt"`
	UploadKey                     []byte               `protobuf:"bytes,100,opt"`
	FileExist                     proto.Option[bool]   `protobuf:"varint,110,opt"`
	PackSize                      proto.Option[int32]  `protobuf:"varint,120,opt"`
	UploadIpList                  []string             `protobuf:"bytes,130,rep"`
	UploadHttpsPort               proto.Option[int32]  `protobuf:"varint,140,opt"`
	UploadHttpsDomain             proto.Option[string] `protobuf:"bytes,150,opt"`
	UploadDns                     proto.Option[string] `protobuf:"bytes,160,opt"`
	UploadLanip                   proto.Option[string] `protobuf:"bytes,170,opt"`
	FileIdCrc                     proto.Option[string] `protobuf:"bytes,200,opt"`
	RtpMediaPlatformUploadAddress []*Addr              `protobuf:"bytes,210,rep"`
	MediaPlatformUploadKey        []byte               `protobuf:"bytes,220,opt"`
}

type Addr struct {
	OutIp     proto.Option[uint32] `protobuf:"varint,1,opt"`
	OutPort   proto.Option[uint32] `protobuf:"varint,2,opt"`
	InnerIp   proto.Option[uint32] `protobuf:"varint,3,opt"`
	InnerPort proto.Option[uint32] `protobuf:"varint,4,opt"`
	IpType    proto.Option[uint32] `protobuf:"varint,5,opt"`
	_         [0]func()
}
