// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/operation/old_code_fetch_group_member.proto

package operation

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type FetchGroupMemberRequest struct {
	GroupUin proto.Option[int64]           `protobuf:"varint,1,opt"`
	Field2   proto.Option[uint32]          `protobuf:"varint,2,opt"`
	Field3   proto.Option[uint32]          `protobuf:"varint,3,opt"`
	Body     *FetchGroupMembersRequestBody `protobuf:"bytes,4,opt"`
	Params   *OidbSvcTrpcScp0XFE7_4Params  `protobuf:"bytes,5,opt"`
	_        [0]func()
}

type OidbSvcTrpcScp0XFE7_4Params struct {
	Uid proto.Option[string] `protobuf:"bytes,2,opt"`
	_   [0]func()
}

type FetchGroupMemberResponse struct {
	GroupUin    proto.Option[int64]              `protobuf:"varint,1,opt"`
	Member      *FetchGroupMembersResponseMember `protobuf:"bytes,2,opt"`
	MemberCount proto.Option[uint32]             `protobuf:"varint,3,opt"`
	_           [0]func()
}
