// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/operation/old_code_sso_readed.proto

package operation

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type SsoReadedReport struct {
	Grp *SsoReadedReportGroup `protobuf:"bytes,1,opt"`
	C2C *SsoReadedReportC2C   `protobuf:"bytes,2,opt"`
	_   [0]func()
}

type SsoReadedReportC2C struct {
	TargetUid proto.Option[string] `protobuf:"bytes,2,opt"`
	Time      int64                `protobuf:"varint,3,opt"`
	StartSeq  uint64               `protobuf:"varint,4,opt"`
	_         [0]func()
}

type SsoReadedReportGroup struct {
	GroupUin uint64 `protobuf:"varint,1,opt"`
	StartSeq uint64 `protobuf:"varint,2,opt"`
	_        [0]func()
}
