// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/operation/old_code_action.proto

package operation

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type SetStatus struct {
	Status        uint32              `protobuf:"varint,1,opt"`
	ExtStatus     uint32              `protobuf:"varint,2,opt"`
	BatteryStatus uint32              `protobuf:"varint,3,opt"` // 电量百分比
	CustomExt     *SetStatusCustomExt `protobuf:"bytes,4,opt"`
	_             [0]func()
}

type SetStatusCustomExt struct {
	FaceId uint32               `protobuf:"varint,1,opt"`
	Text   proto.Option[string] `protobuf:"bytes,2,opt"`
	Field3 uint32               `protobuf:"varint,3,opt"`
	_      [0]func()
}

type SetStatusResponse struct {
	Message string `protobuf:"bytes,2,opt"`
	_       [0]func()
}

// 魔法表情 key
type MarketFaceKeyReq struct {
	Field1 uint32                `protobuf:"varint,1,opt"`
	Info   *MarketFaceKeyReqInfo `protobuf:"bytes,5,opt"`
	_      [0]func()
}

type MarketFaceKeyReqInfo struct {
	FaceIds []string `protobuf:"bytes,3,rep"`
}

type MarketFaceKeyRsp struct {
	Info *MarketFaceKeyRspInfo `protobuf:"bytes,5,opt"`
	_    [0]func()
}

type MarketFaceKeyRspInfo struct {
	Keys []string `protobuf:"bytes,1,rep"`
}
