// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/operation/set_group_reaction.proto

package operation

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type SetGroupReactionRequest struct {
	GroupUin proto.Option[int64]  `protobuf:"varint,2,opt"`
	Sequence proto.Option[uint64] `protobuf:"varint,3,opt"`
	Code     proto.Option[string] `protobuf:"bytes,4,opt"`
	Type     proto.Option[uint64] `protobuf:"varint,5,opt"`
	_        [0]func()
}

type SetGroupReactionResponse struct {
	_ [0]func()
}
