// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/operation/set_group_notification.proto

package operation

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type SetGroupNotificationRequest struct {
	Operate proto.Option[uint64]             `protobuf:"varint,1,opt"`
	Body    *SetGroupNotificationRequestBody `protobuf:"bytes,2,opt"`
	_       [0]func()
}

type SetGroupNotificationRequestBody struct {
	Sequence proto.Option[uint64] `protobuf:"varint,1,opt"`
	Type     proto.Option[uint64] `protobuf:"varint,2,opt"`
	GroupUin proto.Option[int64]  `protobuf:"varint,3,opt"`
	Message  proto.Option[string] `protobuf:"bytes,4,opt"`
	_        [0]func()
}

type SetGroupNotificationResponse struct {
	_ [0]func()
}
