// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: system/system.proto

package system

import (
	proto "github.com/RomiChan/protobuf/proto"
	message "github.com/kernel-ai/koscore/client/packets/pb/v2/message"
)

type InfoSyncPush struct {
	Result              proto.Option[uint32]      `protobuf:"varint,1,opt"`
	ErrMsg              proto.Option[string]      `protobuf:"bytes,2,opt"`
	PushFlag            proto.Option[uint32]      `protobuf:"varint,3,opt"`
	PushSeq             proto.Option[uint32]      `protobuf:"varint,4,opt"`
	RetryFlag           proto.Option[uint32]      `protobuf:"varint,5,opt"`
	GroupNodes          []*GroupNode              `protobuf:"bytes,6,rep"`
	Notifications       *GroupSystemNotifications `protobuf:"bytes,7,opt"`
	SysNotifications    *SystemNotifications      `protobuf:"bytes,8,opt"`
	UseInitCacheData    proto.Option[uint32]      `protobuf:"varint,10,opt"`
	GuildNodes          *GuildNode                `protobuf:"bytes,11,opt"`
	DiscussListFlag     proto.Option[uint32]      `protobuf:"varint,12,opt"`
	RoamMsgOptimizeFlag proto.Option[uint32]      `protobuf:"varint,13,opt"`
	GroupGuildFlag      proto.Option[uint32]      `protobuf:"varint,14,opt"`
}

type GroupNode struct {
	GroupCode               proto.Option[uint64] `protobuf:"varint,1,opt"`
	GroupSeq                proto.Option[uint64] `protobuf:"varint,2,opt"`
	ReadMsgSeq              proto.Option[uint64] `protobuf:"varint,3,opt"`
	Mask                    proto.Option[uint64] `protobuf:"varint,4,opt"`
	LongestMsgTime          proto.Option[uint64] `protobuf:"varint,5,opt"`
	HasMessage              proto.Option[bool]   `protobuf:"varint,6,opt"`
	LatestMsgTime           proto.Option[uint64] `protobuf:"varint,8,opt"`
	PeerName                proto.Option[string] `protobuf:"bytes,9,opt"`
	LongestMsgSeq           proto.Option[uint64] `protobuf:"varint,10,opt"`
	UinFlagEx2              proto.Option[uint64] `protobuf:"varint,11,opt"`
	ImportantMsgLatestSeq   proto.Option[uint32] `protobuf:"varint,12,opt"`
	GroupMaxEventSeq        proto.Option[uint32] `protobuf:"varint,13,opt"`
	Random                  proto.Option[uint32] `protobuf:"varint,14,opt"`
	NeedToCheckSeqOnAioOpen proto.Option[uint32] `protobuf:"varint,15,opt"`
	_                       [0]func()
}

type GuildNode struct {
	PeerId proto.Option[uint64] `protobuf:"varint,1,opt"`
	_      [0]func()
}

type GroupSystemNotifications struct {
	Infos []*GroupSystemNotificationsInfo `protobuf:"bytes,3,rep"`
}

type SystemNotifications struct {
	Infos []*SystemNotificationsInfo `protobuf:"bytes,4,rep"`
}

type GroupSystemNotificationsInfo struct {
	GroupCode          proto.Option[int64]      `protobuf:"varint,3,opt"`
	StartSeq           proto.Option[uint32]     `protobuf:"varint,4,opt"`
	EndSeq             proto.Option[uint32]     `protobuf:"varint,5,opt"`
	Messages           []*message.CommonMessage `protobuf:"bytes,6,rep"`
	LastSpeakTimestamp proto.Option[int64]      `protobuf:"varint,8,opt"`
}

type SystemNotificationsInfo struct {
	PeerUin            proto.Option[int64]      `protobuf:"varint,1,opt"`
	PeerUid            proto.Option[string]     `protobuf:"bytes,2,opt"`
	LastSpeakTimestamp proto.Option[int64]      `protobuf:"varint,5,opt"`
	Messages           []*message.CommonMessage `protobuf:"bytes,8,rep"`
}

type SsoHeartBeatRequest struct {
	Type         proto.Option[uint32] `protobuf:"varint,1,opt"`
	LocalSilence *SilenceState        `protobuf:"bytes,2,opt"`
	BatteryState proto.Option[uint32] `protobuf:"varint,3,opt"`
	Time         proto.Option[uint64] `protobuf:"varint,4,opt"`
	_            [0]func()
}

type SsoHeartBeatResponse struct {
	Interval proto.Option[uint64] `protobuf:"varint,3,opt"`
	_        [0]func()
}

type SilenceState struct {
	LocalSilence proto.Option[uint32] `protobuf:"varint,1,opt"`
	_            [0]func()
}

type PushParams struct {
	OnlineDevices       []*OnlineDevice      `protobuf:"bytes,4,rep"`
	GuildParams         *GuildParams         `protobuf:"bytes,6,opt"`
	ErrMsg              proto.Option[string] `protobuf:"bytes,7,opt"`
	GroupMsgStorageTime proto.Option[uint32] `protobuf:"varint,9,opt"`
}

type GuildParams struct {
	GuildFlag       proto.Option[uint32] `protobuf:"varint,1,opt"`
	GuildSwitchFlag proto.Option[uint32] `protobuf:"varint,2,opt"`
	_               [0]func()
}

type OnlineDevice struct {
	InstId        proto.Option[uint32] `protobuf:"varint,1,opt"`
	ClientType    proto.Option[uint32] `protobuf:"varint,2,opt"`
	State         proto.Option[uint32] `protobuf:"varint,3,opt"`
	PlatId        proto.Option[uint32] `protobuf:"varint,4,opt"`
	PlatType      proto.Option[string] `protobuf:"bytes,5,opt"`
	NewClientType proto.Option[uint32] `protobuf:"varint,6,opt"`
	DeviceName    proto.Option[string] `protobuf:"bytes,7,opt"`
	_             [0]func()
}

type SsoC2CMsgCookie struct {
	C2CLastMsgTime proto.Option[uint64] `protobuf:"varint,1,opt"`
	_              [0]func()
}

type SsoC2CSyncInfo struct {
	C2CMsgCookie     *SsoC2CMsgCookie     `protobuf:"bytes,1,opt"`
	C2CLastMsgTime   proto.Option[uint64] `protobuf:"varint,2,opt"`
	LastC2CMsgCookie *SsoC2CMsgCookie     `protobuf:"bytes,3,opt"`
	_                [0]func()
}

type DeviceInfo struct {
	DevName      proto.Option[string] `protobuf:"bytes,1,opt"`
	DevType      proto.Option[string] `protobuf:"bytes,2,opt"`
	OsVer        proto.Option[string] `protobuf:"bytes,3,opt"`
	Brand        proto.Option[string] `protobuf:"bytes,4,opt"`
	VendorOsName proto.Option[string] `protobuf:"bytes,5,opt"`
	_            [0]func()
}

type OnlineBusinessInfo struct {
	NotifySwitch        proto.Option[uint32] `protobuf:"varint,1,opt"`
	BindUinNotifySwitch proto.Option[uint32] `protobuf:"varint,2,opt"`
	_                   [0]func()
}

type RegisterInfo struct {
	Guid                       proto.Option[string] `protobuf:"bytes,1,opt"`
	KickPc                     proto.Option[uint32] `protobuf:"varint,2,opt"`
	BuildVer                   proto.Option[string] `protobuf:"bytes,3,opt"`
	IsFirstRegisterProxyOnline proto.Option[uint32] `protobuf:"varint,4,opt"`
	LocaleId                   proto.Option[uint32] `protobuf:"varint,5,opt"`
	DeviceInfo                 *DeviceInfo          `protobuf:"bytes,6,opt"`
	SetMute                    proto.Option[uint32] `protobuf:"varint,7,opt"`
	RegisterVendorType         proto.Option[uint32] `protobuf:"varint,8,opt"`
	RegType                    proto.Option[uint32] `protobuf:"varint,9,opt"`
	BusinessInfo               *OnlineBusinessInfo  `protobuf:"bytes,10,opt"`
	BatteryStatus              proto.Option[uint32] `protobuf:"varint,11,opt"`
	Field12                    proto.Option[int32]  `protobuf:"varint,12,opt"`
	_                          [0]func()
}

type NormalConfig struct {
	IntCfg map[uint32]int32 `protobuf:"bytes,1,rep" protobuf_key:"varint,1,opt" protobuf_val:"varint,2,opt"`
}

type CurAppState struct {
	IsDelayRequest proto.Option[uint32] `protobuf:"varint,1,opt"`
	AppStatus      proto.Option[uint32] `protobuf:"varint,2,opt"`
	SilenceStatus  proto.Option[uint32] `protobuf:"varint,3,opt"`
	_              [0]func()
}

type SsoInfoSyncRequest struct {
	SyncFlag         proto.Option[uint32] `protobuf:"varint,1,opt"`
	ReqRandom        proto.Option[uint32] `protobuf:"varint,2,opt"`
	CurActiveStatus  proto.Option[uint32] `protobuf:"varint,4,opt"`
	GroupLastMsgTime proto.Option[uint64] `protobuf:"varint,5,opt"`
	C2CSyncInfo      *SsoC2CSyncInfo      `protobuf:"bytes,6,opt"`
	NormalConfig     *NormalConfig        `protobuf:"bytes,8,opt"`
	RegisterInfo     *RegisterInfo        `protobuf:"bytes,9,opt"`
	Unknown          map[uint32]uint32    `protobuf:"bytes,10,rep" protobuf_key:"varint,1,opt" protobuf_val:"varint,2,opt"`
	AppState         *CurAppState         `protobuf:"bytes,11,opt"`
}

type RegisterResponse struct {
	Msg proto.Option[string] `protobuf:"bytes,2,opt"`
	_   [0]func()
}

type SsoSyncInfoResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,7,opt"`
	_                [0]func()
}

type SsoUnregister struct {
	RegType     proto.Option[int32] `protobuf:"varint,1,opt"`
	DeviceInfo  *DeviceInfo         `protobuf:"bytes,2,opt"`
	UserTrigger proto.Option[int32] `protobuf:"varint,3,opt"`
	_           [0]func()
}

type ThirdPartyLoginResponse struct {
	Seq        proto.Option[uint64] `protobuf:"varint,1,opt"`
	CommonInfo *RespCommonInfo      `protobuf:"bytes,9,opt"`
	_          [0]func()
}

type RespCommonInfo struct {
	NeedVerifyScenes proto.Option[uint32] `protobuf:"varint,10,opt"`
	RspNt            *RspNT               `protobuf:"bytes,11,opt"`
	A1Seq            proto.Option[uint32] `protobuf:"varint,12,opt"`
	_                [0]func()
}

type RspNT struct {
	Uid proto.Option[string] `protobuf:"bytes,1,opt"`
	Ua2 []byte               `protobuf:"bytes,2,opt"`
}
