// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: login/nt_ecdh.proto

package login

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type KeyExchangeRequest struct {
	PublicKey  []byte               `protobuf:"bytes,1,opt"`
	Type       proto.Option[uint32] `protobuf:"varint,2,opt"`
	Secret     []byte               `protobuf:"bytes,3,opt"`
	Timestamp  proto.Option[int64]  `protobuf:"varint,4,opt"`
	VerifyHash []byte               `protobuf:"bytes,5,opt"`
}

type KeyExchangeResponse struct {
	Secret    []byte `protobuf:"bytes,1,opt"`
	Field2    []byte `protobuf:"bytes,2,opt"`
	PublicKey []byte `protobuf:"bytes,3,opt"`
}

type KeyExchangeRequestBuf struct {
	Uin  proto.Option[string] `protobuf:"bytes,1,opt"`
	Guid []byte               `protobuf:"bytes,2,opt"`
}

type KeyExchangeResponseSecret struct {
	SessionKey    []byte               `protobuf:"bytes,1,opt"`
	SessionTicket []byte               `protobuf:"bytes,2,opt"`
	Expiration    proto.Option[uint32] `protobuf:"varint,3,opt"`
}

type NTLoginForwardRequest struct {
	SessionTicket []byte               `protobuf:"bytes,1,opt"`
	Buffer        []byte               `protobuf:"bytes,3,opt"`
	Type          proto.Option[uint32] `protobuf:"varint,4,opt"`
	SecBuffer     []byte               `protobuf:"bytes,5,opt"`
}
