// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: login/nt_login_enum.proto

package login

type NTLoginPlatform = int32

const (
	NTLoginPlatform_UNKNOWN NTLoginPlatform = 0
	NTLoginPlatform_IOS     NTLoginPlatform = 1
	NTLoginPlatform_ANDROID NTLoginPlatform = 2
	NTLoginPlatform_SYMBIAN NTLoginPlatform = 3
	NTLoginPlatform_WINDOWS NTLoginPlatform = 4
	NTLoginPlatform_MAC     NTLoginPlatform = 5
	NTLoginPlatform_IPAD    NTLoginPlatform = 6
	NTLoginPlatform_LINUX   NTLoginPlatform = 7
	NTLoginPlatform_HARMONY NTLoginPlatform = 8
)

type NTLoginRetCode = int32

const (
	NTLoginRetCode_SUCCESS                                 NTLoginRetCode = 0
	NTLoginRetCode_ERROR_DEFAULT                           NTLoginRetCode = 140022000
	NTLoginRetCode_ERROR_INVALID_PARAMETER                 NTLoginRetCode = 140022001
	NTLoginRetCode_ERROR_SYSTEM_FAILED                     NTLoginRetCode = 140022002
	NTLoginRetCode_ERROR_TIMEOUT_RETRY                     NTLoginRetCode = 140022003
	NTLoginRetCode_ERROR_NEED_UPDATE                       NTLoginRetCode = 140022004
	NTLoginRetCode_ERROR_FROZEN                            NTLoginRetCode = 140022005
	NTLoginRetCode_ERROR_PROTECT                           NTLoginRetCode = 140022006
	NTLoginRetCode_ERROR_STRICT                            NTLoginRetCode = 140022007
	NTLoginRetCode_ERROR_PROOF_WATER                       NTLoginRetCode = 140022008
	NTLoginRetCode_ERROR_REFUSE_PASSWORD_LOGIN             NTLoginRetCode = 140022009
	NTLoginRetCode_ERROR_NEW_DEVICE                        NTLoginRetCode = 140022010
	NTLoginRetCode_ERROR_UNUSUAL_DEVICE                    NTLoginRetCode = 140022011
	NTLoginRetCode_ERROR_INVALID_COOKIE                    NTLoginRetCode = 140022012
	NTLoginRetCode_ERROR_ACCOUNT_OR_PASSWORD_ERROR         NTLoginRetCode = 140022013
	NTLoginRetCode_ERROR_EXPIRE_TICKET                     NTLoginRetCode = 140022014
	NTLoginRetCode_ERROR_KICKED_TICKET                     NTLoginRetCode = 140022015
	NTLoginRetCode_ERROR_ILLEGAL_TICKET                    NTLoginRetCode = 140022016
	NTLoginRetCode_ERROR_SEC_BEAT                          NTLoginRetCode = 140022017
	NTLoginRetCode_ERROR_ACCOUNT_NOT_UIN                   NTLoginRetCode = 140022018
	NTLoginRetCode_ERROR_NEED_VERIFY_REAL_NAME             NTLoginRetCode = 140022019
	NTLoginRetCode_ERROR_NICE_ACCOUNT_EXPIRED              NTLoginRetCode = 150022020
	NTLoginRetCode_ERROR_BLACK_ACCOUNT                     NTLoginRetCode = 150022021
	NTLoginRetCode_ERROR_TOO_OFTEN                         NTLoginRetCode = 150022022
	NTLoginRetCode_ERROR_TOO_MANY_TIMES_TODAY              NTLoginRetCode = 150022023
	NTLoginRetCode_ERROR_UNREGISTERED                      NTLoginRetCode = 150022024
	NTLoginRetCode_ERROR_NICE_ACCOUNT_PARENT_CHILD_EXPIRED NTLoginRetCode = 150022025
	NTLoginRetCode_ERROR_SMS_INVALID                       NTLoginRetCode = 150022026
	NTLoginRetCode_ERROR_TGTGT_EXCHANGE_A1_FORBID          NTLoginRetCode = 150022027
	NTLoginRetCode_ERROR_REMIND_CANCELLED_STATUS           NTLoginRetCode = 150022028
	NTLoginRetCode_ERROR_MULTIPLE_PASSWORD_INCORRECT       NTLoginRetCode = 150022029
)

type NTLoginPasswordVerifyResult = int32

const (
	NTLoginPasswordVerifyResult_ERROR_SUCCESS  NTLoginPasswordVerifyResult = 0
	NTLoginPasswordVerifyResult_ERROR_SCAN     NTLoginPasswordVerifyResult = 1
	NTLoginPasswordVerifyResult_ERROR_PASSWORD NTLoginPasswordVerifyResult = 2
)

type NTLoginCodeType = int32

const (
	NTLoginCodeType_AUTHCODE NTLoginCodeType = 0
	NTLoginCodeType_TGT      NTLoginCodeType = 1
	NTLoginCodeType_A2       NTLoginCodeType = 2
	NTLoginCodeType_TGTGT    NTLoginCodeType = 3
)
