// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: login/nt_login.proto

package login

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type NTLoginHead struct {
	UserInfo     *NTLoginUserInfo     `protobuf:"bytes,1,opt"`
	ClientInfo   *NTLoginClientInfo   `protobuf:"bytes,2,opt"`
	AppInfo      *NTLoginAppInfo      `protobuf:"bytes,3,opt"`
	ErrorInfo    *NTLoginErrorInfo    `protobuf:"bytes,4,opt"`
	Cookie       *NTLoginCookie       `protobuf:"bytes,5,opt"`
	SecurityInfo *NTLoginSecurityInfo `protobuf:"bytes,6,opt"`
	SdkInfo      *NTLoginSdkInfo      `protobuf:"bytes,7,opt"`
	LongCookie   *NTLoginLongCookie   `protobuf:"bytes,8,opt"`
	_            [0]func()
}

type NTLoginUserInfo struct {
	Account     proto.Option[string] `protobuf:"bytes,1,opt"`
	CountryCode proto.Option[uint32] `protobuf:"varint,2,opt"`
	_           [0]func()
}

type NTLoginClientInfo struct {
	DeviceType proto.Option[string]          `protobuf:"bytes,1,opt"`
	DeviceName proto.Option[string]          `protobuf:"bytes,2,opt"`
	Platform   proto.Option[NTLoginPlatform] `protobuf:"varint,3,opt"`
	Guid       []byte                        `protobuf:"bytes,4,opt"`
	Pubno      proto.Option[uint32]          `protobuf:"varint,5,opt"`
	ClientVer  proto.Option[uint32]          `protobuf:"varint,6,opt"`
	ClientType proto.Option[uint32]          `protobuf:"varint,7,opt"`
	SsoVer     proto.Option[uint32]          `protobuf:"varint,8,opt"`
}

type NTLoginAppInfo struct {
	Version         proto.Option[string] `protobuf:"bytes,1,opt"`
	AppId           proto.Option[int32]  `protobuf:"varint,2,opt"`
	AppName         proto.Option[string] `protobuf:"bytes,3,opt"`
	ClientA1Version proto.Option[uint32] `protobuf:"varint,4,opt"`
	Qua             proto.Option[string] `protobuf:"bytes,5,opt"`
	OpenInfo        *NTLoginOpenInfo     `protobuf:"bytes,6,opt"`
	_               [0]func()
}

type NTLoginOpenInfo struct {
	AppId proto.Option[uint32] `protobuf:"varint,1,opt"`
	_     [0]func()
}

type NTLoginSdkInfo struct {
	Version proto.Option[uint32] `protobuf:"varint,1,opt"`
	_       [0]func()
}

type NTLoginSecurityInfo struct {
	_ [0]func()
}

type NTLoginCookie struct {
	CookieContent proto.Option[string] `protobuf:"bytes,1,opt"`
	_             [0]func()
}

type NTLoginLongCookie struct {
	Content []byte `protobuf:"bytes,1,opt"`
}

type NTLoginErrorInfo struct {
	ErrCode        proto.Option[uint64] `protobuf:"varint,1,opt"`
	StrTipsTitle   proto.Option[string] `protobuf:"bytes,2,opt"`
	StrTipsContent proto.Option[string] `protobuf:"bytes,3,opt"`
	StrJumpWording proto.Option[string] `protobuf:"bytes,4,opt"`
	StrJumpUrl     proto.Option[string] `protobuf:"bytes,5,opt"`
	MsgDetail      *NTLoginErrorDetail  `protobuf:"bytes,6,opt"`
	RptMsgButton   []*NTLoginButton     `protobuf:"bytes,7,rep"`
}

type NTLoginErrorDetail struct {
	MsgNeedVerifyNewDevice *NTLoginErrorNeedVerifyNewDevice `protobuf:"bytes,1,opt"`
	MsgUnregistered        *NTLoginErrorUnregistered        `protobuf:"bytes,2,opt"`
	MsgBeenForbiden        *NTLoginErrorBeenForbiden        `protobuf:"bytes,3,opt"`
	MsgNiceAccountExpire   *NTLoginErrorNiceAccountExpire   `protobuf:"bytes,4,opt"`
	_                      [0]func()
}

type NTLoginErrorNeedVerifyNewDevice struct {
	AllowGateWayVerify proto.Option[bool] `protobuf:"varint,1,opt"`
	_                  [0]func()
}

type NTLoginErrorUnregistered struct {
	UnregisteredSig proto.Option[string] `protobuf:"bytes,1,opt"`
	_               [0]func()
}

type NTLoginErrorBeenForbiden struct {
	Area proto.Option[uint32] `protobuf:"varint,1,opt"`
	_    [0]func()
}

type NTLoginErrorNiceAccountExpire struct {
	ExpireSig proto.Option[string] `protobuf:"bytes,1,opt"`
	_         [0]func()
}

type NTLoginButton struct {
	Wording proto.Option[string] `protobuf:"bytes,1,opt"`
	Url     proto.Option[string] `protobuf:"bytes,2,opt"`
	_       [0]func()
}

type NTLoginCommonInfo struct {
	Face    proto.Option[uint32] `protobuf:"varint,1,opt"`
	Nick    proto.Option[string] `protobuf:"bytes,2,opt"`
	Gender  proto.Option[uint32] `protobuf:"varint,3,opt"`
	Flag    proto.Option[uint32] `protobuf:"varint,4,opt"`
	Age     proto.Option[uint32] `protobuf:"varint,5,opt"`
	SvrFlag proto.Option[int32]  `protobuf:"varint,6,opt"`
	_       [0]func()
}

type NTLoginTgtInfo struct {
	Tgt                []byte               `protobuf:"bytes,1,opt"`
	GtkeyTgt           []byte               `protobuf:"bytes,2,opt"`
	TgtVer             proto.Option[uint32] `protobuf:"varint,3,opt"`
	Priority           proto.Option[uint64] `protobuf:"varint,4,opt"`
	RefreshInterval    proto.Option[uint64] `protobuf:"varint,5,opt"`
	ValidateInterval   proto.Option[uint64] `protobuf:"varint,6,opt"`
	TryRefreshInterval proto.Option[uint64] `protobuf:"varint,7,opt"`
	TryRefreshCount    proto.Option[uint64] `protobuf:"varint,8,opt"`
	DstAppid           proto.Option[uint64] `protobuf:"varint,9,opt"`
	GtkeyTgtpwd        []byte               `protobuf:"bytes,10,opt"`
	CommInfo           *NTLoginCommonInfo   `protobuf:"bytes,11,opt"`
	SigSession         []byte               `protobuf:"bytes,12,opt"`
	SigSessionKey      []byte               `protobuf:"bytes,13,opt"`
	NextRefreshGap     proto.Option[uint64] `protobuf:"varint,14,opt"`
}

type NTLoginSTInfo struct {
	St      []byte `protobuf:"bytes,1,opt"`
	GtkeySt []byte `protobuf:"bytes,2,opt"`
}

type NTLoginSTHttpInfo struct {
	AllowPtlogin proto.Option[uint32] `protobuf:"varint,1,opt"`
	StHttp       []byte               `protobuf:"bytes,2,opt"`
	GtkeyStHttp  []byte               `protobuf:"bytes,3,opt"`
}

type NTLoginControlRefreshTime struct {
	NextStartRefreshTime proto.Option[uint64] `protobuf:"varint,1,opt"`
	ExpireTime           proto.Option[uint64] `protobuf:"varint,2,opt"`
	_                    [0]func()
}

type NTLoginTickets struct {
	A1            []byte                     `protobuf:"bytes,3,opt"`
	A2            []byte                     `protobuf:"bytes,4,opt"`
	D2            []byte                     `protobuf:"bytes,5,opt"`
	D2Key         []byte                     `protobuf:"bytes,6,opt"`
	AuthCode      []byte                     `protobuf:"bytes,7,opt"`
	TgtInfo       *NTLoginTgtInfo            `protobuf:"bytes,8,opt"`
	StInfo        *NTLoginSTInfo             `protobuf:"bytes,9,opt"`
	SecExtra      []byte                     `protobuf:"bytes,10,opt"`
	StHttpInfo    *NTLoginSTHttpInfo         `protobuf:"bytes,11,opt"`
	A1RefreshTime *NTLoginControlRefreshTime `protobuf:"bytes,12,opt"`
	Nopicsig      []byte                     `protobuf:"bytes,13,opt"`
	A1Key         []byte                     `protobuf:"bytes,14,opt"`
	A1Seq         proto.Option[uint64]       `protobuf:"varint,15,opt"`
	A2RefreshTime *NTLoginControlRefreshTime `protobuf:"bytes,16,opt"`
	A2Key         []byte                     `protobuf:"bytes,17,opt"`
}

type NTLoginUserProfile struct {
	NickName                []byte             `protobuf:"bytes,1,opt"`
	RegisterWithoutPassword proto.Option[bool] `protobuf:"varint,2,opt"`
}

type NTLoginAccoutInfo struct {
	Uin         proto.Option[uint64] `protobuf:"varint,1,opt"`
	Uid         proto.Option[string] `protobuf:"bytes,2,opt"`
	UserProfile *NTLoginUserProfile  `protobuf:"bytes,3,opt"`
	_           [0]func()
}

type NTLoginIframe struct {
	IframeSig     proto.Option[string] `protobuf:"bytes,1,opt"`
	IframeRandstr proto.Option[string] `protobuf:"bytes,2,opt"`
	IframeSid     proto.Option[string] `protobuf:"bytes,3,opt"`
	_             [0]func()
}

type NTLoginSecProtect struct {
	NewDeviceCheckSig     []byte               `protobuf:"bytes,1,opt"`
	UnusualDeviceCheckSig []byte               `protobuf:"bytes,2,opt"`
	UnusualDeviceQrSig    proto.Option[string] `protobuf:"bytes,3,opt"`
	UinToken              proto.Option[string] `protobuf:"bytes,4,opt"`
}

type NTLoginSecCheck struct {
	IframeUrl proto.Option[string] `protobuf:"bytes,3,opt"`
	_         [0]func()
}

type NTLoginLoginProcessReqBody struct {
	NeedRemindCancellatedStatus proto.Option[bool] `protobuf:"varint,1,opt"`
	_                           [0]func()
}

type NTLoginLoginProcessRspBody struct {
	_ [0]func()
}

type NTLoginPasswordLoginReqBody struct {
	A1                       []byte                      `protobuf:"bytes,1,opt"`
	Iframe                   *NTLoginIframe              `protobuf:"bytes,2,opt"`
	NewDeviceCheckSucceedSig []byte                      `protobuf:"bytes,3,opt"`
	RegisterSucceedSig       proto.Option[string]        `protobuf:"bytes,4,opt"`
	LoginProcessReq          *NTLoginLoginProcessReqBody `protobuf:"bytes,5,opt"`
}

type NTLoginPasswordLoginRspBody struct {
	Tickets         *NTLoginTickets             `protobuf:"bytes,1,opt"`
	SecCheck        *NTLoginSecCheck            `protobuf:"bytes,2,opt"`
	SecProtect      *NTLoginSecProtect          `protobuf:"bytes,3,opt"`
	Account         *NTLoginAccoutInfo          `protobuf:"bytes,4,opt"`
	LoginProcessRsp *NTLoginLoginProcessRspBody `protobuf:"bytes,5,opt"`
	_               [0]func()
}

type NTLoginPasswordLoginNewDeviceReqBody struct {
	NewDeviceCheckSucceedSig []byte `protobuf:"bytes,1,opt"`
}

type NTLoginPasswordLoginNewDeviceRspBody struct {
	Tickets *NTLoginTickets    `protobuf:"bytes,1,opt"`
	Account *NTLoginAccoutInfo `protobuf:"bytes,3,opt"`
	_       [0]func()
}

type NTLoginPasswordLoginUnusualDeviceReqBody struct {
	A1                           []byte `protobuf:"bytes,1,opt"`
	UnusualDeviceCheckSucceedSig []byte `protobuf:"bytes,2,opt"`
}

type NTLoginPasswordLoginUnusualDeviceRspBody struct {
	Tickets *NTLoginTickets    `protobuf:"bytes,1,opt"`
	Account *NTLoginAccoutInfo `protobuf:"bytes,2,opt"`
	_       [0]func()
}

type NTLoginEasyLoginReqBody struct {
	A1 []byte `protobuf:"bytes,1,opt"`
}

type NTLoginEasyLoginRspBody struct {
	Tickets    *NTLoginTickets    `protobuf:"bytes,1,opt"`
	SecCheck   *NTLoginSecCheck   `protobuf:"bytes,2,opt"`
	SecProtect *NTLoginSecProtect `protobuf:"bytes,3,opt"`
	_          [0]func()
}

type NTLoginEasyLoginUnusualDeviceReqBody struct {
	A1                           []byte `protobuf:"bytes,1,opt"`
	UnusualDeviceCheckSucceedSig []byte `protobuf:"bytes,2,opt"`
}

type NTLoginEasyLoginUnusualDeviceRspBody struct {
	Tickets *NTLoginTickets `protobuf:"bytes,1,opt"`
	_       [0]func()
}

type NTLoginTGTExchangeFastLoginReqBody struct {
	Tgt      []byte                        `protobuf:"bytes,1,opt"`
	SecExtra []byte                        `protobuf:"bytes,2,opt"`
	CodeType proto.Option[NTLoginCodeType] `protobuf:"varint,3,opt"`
}

type NTLoginTGTExchangeFastLoginRspBody struct {
	Tickets *NTLoginTickets `protobuf:"bytes,1,opt"`
	_       [0]func()
}

type NTLoginRefreshTicketReqBody struct {
	A1       []byte `protobuf:"bytes,1,opt"`
	Nopicsig []byte `protobuf:"bytes,2,opt"`
}

type NTLoginRefreshTicketRspBody struct {
	Tickets *NTLoginTickets    `protobuf:"bytes,1,opt"`
	Account *NTLoginAccoutInfo `protobuf:"bytes,2,opt"`
	_       [0]func()
}

type NTLoginRefreshA2ReqBody struct {
	A2    []byte `protobuf:"bytes,1,opt"`
	D2    []byte `protobuf:"bytes,2,opt"`
	D2Key []byte `protobuf:"bytes,3,opt"`
}

type NTLoginRefreshA2RspBody struct {
	Tickets *NTLoginTickets    `protobuf:"bytes,1,opt"`
	Account *NTLoginAccoutInfo `protobuf:"bytes,2,opt"`
	_       [0]func()
}

type NTLoginCommon struct {
	Head *NTLoginHead `protobuf:"bytes,1,opt"`
	Body []byte       `protobuf:"bytes,2,opt"`
}

type NTLoginAndroidExt struct {
	Field1 proto.Option[int32]  `protobuf:"varint,1,opt"`
	Uin    proto.Option[string] `protobuf:"bytes,2,opt"`
	_      [0]func()
}

type NTLoginAndroidCommon struct {
	Common *NTLoginCommon     `protobuf:"bytes,2,opt"`
	Ext    *NTLoginAndroidExt `protobuf:"bytes,3,opt"`
	_      [0]func()
}
