// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: login/qr_login_ext_info.proto

package login

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type DevInfo struct {
	DevType proto.Option[string] `protobuf:"bytes,1,opt"`
	DevName proto.Option[string] `protobuf:"bytes,2,opt"`
	_       [0]func()
}

type GenInfo struct {
	ClientType  proto.Option[uint32] `protobuf:"varint,1,opt"`
	ClientVer   proto.Option[uint32] `protobuf:"varint,2,opt"`
	ClientAppid proto.Option[uint32] `protobuf:"varint,3,opt"`
	Field6      proto.Option[uint32] `protobuf:"varint,6,opt"`
	_           [0]func()
}

type QrExtInfo struct {
	DevInfo *DevInfo             `protobuf:"bytes,1,opt"`
	QrUrl   proto.Option[string] `protobuf:"bytes,2,opt"`
	QrSig   proto.Option[string] `protobuf:"bytes,3,opt"`
	GenInfo *GenInfo             `protobuf:"bytes,4,opt"`
	_       [0]func()
}

type ScanExtInfo struct {
	Guid                 []byte               `protobuf:"bytes,1,opt"`
	Imei                 proto.Option[string] `protobuf:"bytes,2,opt"`
	ScanScene            proto.Option[uint32] `protobuf:"varint,3,opt"`
	AllowAutoRenewTicket proto.Option[bool]   `protobuf:"varint,4,opt"`
	InvalidGenTicket     proto.Option[bool]   `protobuf:"varint,5,opt"`
}
