// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: login/qr_login.proto

package login

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type QrLogin struct {
	ScanResult          proto.Option[uint32] `protobuf:"varint,1,opt"`
	SafeInfo            *SafeInfo            `protobuf:"bytes,2,opt"`
	RiskInfo            *RiskInfo            `protobuf:"bytes,3,opt"`
	RejectInfo          *RejectInfo          `protobuf:"bytes,4,opt"`
	TipsCtrl            *TipsCtrl            `protobuf:"bytes,5,opt"`
	AutoRenewTicketInfo *AutoRenewTicketInfo `protobuf:"bytes,6,opt"`
	_                   [0]func()
}

type SafeInfo struct {
	TipsTemplate    proto.Option[string] `protobuf:"bytes,1,opt"`
	LoginLoc        proto.Option[string] `protobuf:"bytes,2,opt"`
	AppName         proto.Option[string] `protobuf:"bytes,3,opt"`
	NewTipsTemplate proto.Option[string] `protobuf:"bytes,4,opt"`
	_               [0]func()
}

type RiskInfo struct {
	TipsTemplate    proto.Option[string] `protobuf:"bytes,1,opt"`
	LoginLoc        proto.Option[string] `protobuf:"bytes,2,opt"`
	AppName         proto.Option[string] `protobuf:"bytes,3,opt"`
	NewTipsTemplate proto.Option[string] `protobuf:"bytes,4,opt"`
	_               [0]func()
}

type RejectInfo struct {
	Tips proto.Option[string] `protobuf:"bytes,1,opt"`
	_    [0]func()
}

type AutoRenewTicketInfo struct {
	IsShowSwitch proto.Option[bool]   `protobuf:"varint,1,opt"`
	IsOpenSwitch proto.Option[bool]   `protobuf:"varint,2,opt"`
	TipsTitle    proto.Option[string] `protobuf:"bytes,3,opt"`
	TipsTemplate proto.Option[string] `protobuf:"bytes,4,opt"`
	_            [0]func()
}

type TipsCtrl struct {
	NormalTipsColor proto.Option[uint32] `protobuf:"varint,1,opt"`
	SecCheck        proto.Option[bool]   `protobuf:"varint,2,opt"`
	SecCheckTips    proto.Option[string] `protobuf:"bytes,3,opt"`
	SecTipsColor    proto.Option[uint32] `protobuf:"varint,4,opt"`
	_               [0]func()
}
