// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: login/tlv.proto

package login

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type DeviceReport struct {
	Bootloader   proto.Option[string] `protobuf:"bytes,1,opt"`
	ProcVersion  proto.Option[string] `protobuf:"bytes,2,opt"`
	CodeName     proto.Option[string] `protobuf:"bytes,3,opt"`
	Incremental  proto.Option[string] `protobuf:"bytes,4,opt"`
	Fingerprint  proto.Option[string] `protobuf:"bytes,5,opt"`
	BootId       proto.Option[string] `protobuf:"bytes,6,opt"`
	AndroidId    proto.Option[string] `protobuf:"bytes,7,opt"`
	BaseBand     proto.Option[string] `protobuf:"bytes,8,opt"`
	InnerVersion proto.Option[string] `protobuf:"bytes,9,opt"`
	_            [0]func()
}
