// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: session.proto

package auth

type Session struct {
	Sig      *WLoginSigs `protobuf:"bytes,1,opt"`
	State    *State      `protobuf:"bytes,2,opt"`
	Info     *BotInfo    `protobuf:"bytes,3,opt"`
	Sequence uint32      `protobuf:"varint,4,opt"`
	_        [0]func()
}

type WLoginSigs struct {
	A1                 []byte            `protobuf:"bytes,1,opt"` // Tlv106
	A1Key              []byte            `protobuf:"bytes,2,opt"` // Tlv10C 16
	A2                 []byte            `protobuf:"bytes,3,opt"` // Tlv10A
	A2Key              []byte            `protobuf:"bytes,4,opt"` // Tlv10D 16
	D2                 []byte            `protobuf:"bytes,5,opt"` // Tlv143
	D2Key              []byte            `protobuf:"bytes,6,opt"` // Tlv305 16
	NoPicSig           []byte            `protobuf:"bytes,7,opt"` // Tlv16A
	TgtgtKey           []byte            `protobuf:"bytes,8,opt"`
	Ksid               []byte            `protobuf:"bytes,9,opt"`
	SuperKey           []byte            `protobuf:"bytes,10,opt"`
	St                 []byte            `protobuf:"bytes,11,opt"`
	StKey              []byte            `protobuf:"bytes,12,opt"`
	StWeb              []byte            `protobuf:"bytes,13,opt"`
	WtSessionTicket    []byte            `protobuf:"bytes,14,opt"`
	WtSessionTicketKey []byte            `protobuf:"bytes,15,opt"`
	RandomKey          []byte            `protobuf:"bytes,16,opt"` // 16
	SKey               []byte            `protobuf:"bytes,17,opt"`
	PsKey              map[string]string `protobuf:"bytes,18,rep" protobuf_key:"bytes,1,opt" protobuf_val:"bytes,2,opt"`
}

type State struct {
	Tlv104      []byte       `protobuf:"bytes,1,opt"`
	Tlv547      []byte       `protobuf:"bytes,2,opt"`
	Tlv174      []byte       `protobuf:"bytes,3,opt"`
	Cookie      string       `protobuf:"bytes,4,opt"`
	QrSig       []byte       `protobuf:"bytes,5,opt"`
	KeyExchange *KeyExchange `protobuf:"bytes,6,opt"`
}

type KeyExchange struct {
	SessionTicket []byte `protobuf:"bytes,1,opt"`
	SessionKey    []byte `protobuf:"bytes,2,opt"`
}

type BotInfo struct {
	Age    uint32 `protobuf:"varint,1,opt"`
	Gender uint32 `protobuf:"varint,2,opt"`
	Name   string `protobuf:"bytes,3,opt"`
	Uin    uint64 `protobuf:"varint,4,opt"`
	Uid    string `protobuf:"bytes,5,opt"`
	_      [0]func()
}
