// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: service/highway/highway.proto

package highway

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type ReqDataHighwayHead struct {
	MsgBaseHead        *DataHighwayHead     `protobuf:"bytes,1,opt"`
	MsgSegHead         *SegHead             `protobuf:"bytes,2,opt"`
	BytesReqExtendInfo []byte               `protobuf:"bytes,3,opt"`
	Timestamp          proto.Option[uint64] `protobuf:"varint,4,opt"`
	MsgLoginSigHead    *LoginSigHead        `protobuf:"bytes,5,opt"`
}

type RespDataHighwayHead struct {
	MsgBaseHead        *DataHighwayHead     `protobuf:"bytes,1,opt"`
	MsgSegHead         *SegHead             `protobuf:"bytes,2,opt"`
	ErrorCode          proto.Option[uint32] `protobuf:"varint,3,opt"`
	AllowRetry         proto.Option[uint32] `protobuf:"varint,4,opt"`
	CacheCost          proto.Option[uint32] `protobuf:"varint,5,opt"`
	HtCost             proto.Option[uint32] `protobuf:"varint,6,opt"`
	BytesRspExtendInfo []byte               `protobuf:"bytes,7,opt"`
	Timestamp          proto.Option[uint64] `protobuf:"varint,8,opt"`
	Range              proto.Option[uint64] `protobuf:"varint,9,opt"`
	IsReset            proto.Option[uint32] `protobuf:"varint,10,opt"`
}

type DataHighwayHead struct {
	Version    proto.Option[uint32] `protobuf:"varint,1,opt"`
	Uin        proto.Option[string] `protobuf:"bytes,2,opt"`
	Command    proto.Option[string] `protobuf:"bytes,3,opt"`
	Seq        proto.Option[uint32] `protobuf:"varint,4,opt"`
	RetryTimes proto.Option[uint32] `protobuf:"varint,5,opt"`
	AppId      proto.Option[uint32] `protobuf:"varint,6,opt"`
	DataFlag   proto.Option[uint32] `protobuf:"varint,7,opt"`
	CommandId  proto.Option[uint32] `protobuf:"varint,8,opt"`
	BuildVer   []byte               `protobuf:"bytes,9,opt"`
}

type LoginSigHead struct {
	Uint32LoginSigType proto.Option[uint32] `protobuf:"varint,1,opt"`
	BytesLoginSig      []byte               `protobuf:"bytes,2,opt"`
	AppId              proto.Option[uint32] `protobuf:"varint,3,opt"`
}

type SegHead struct {
	ServiceId     proto.Option[uint32] `protobuf:"varint,1,opt"`
	Filesize      proto.Option[uint64] `protobuf:"varint,2,opt"`
	DataOffset    proto.Option[uint64] `protobuf:"varint,3,opt"`
	DataLength    proto.Option[uint32] `protobuf:"varint,4,opt"`
	RetCode       proto.Option[uint32] `protobuf:"varint,5,opt"`
	ServiceTicket []byte               `protobuf:"bytes,6,opt"`
	Md5           []byte               `protobuf:"bytes,8,opt"`
	FileMd5       []byte               `protobuf:"bytes,9,opt"`
	CacheAddr     proto.Option[uint32] `protobuf:"varint,10,opt"`
	CachePort     proto.Option[uint32] `protobuf:"varint,13,opt"`
}
