// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: message/message.proto

package message

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type Elem struct {
	Text           *Text           `protobuf:"bytes,1,opt"`
	Face           *Face           `protobuf:"bytes,2,opt"`
	NotOnlineImage *NotOnlineImage `protobuf:"bytes,4,opt"`
	TransElemInfo  *TransElem      `protobuf:"bytes,5,opt"`
	MarketFace     *MarketFace     `protobuf:"bytes,6,opt"`
	CustomFace     *CustomFace     `protobuf:"bytes,8,opt"`
	RichMsg        *RichMsg        `protobuf:"bytes,12,opt"`
	VideoFile      *VideoFile      `protobuf:"bytes,19,opt"`
	SrcMsg         *SourceMsg      `protobuf:"bytes,45,opt"`
	LightAppElem   *LightAppElem   `protobuf:"bytes,51,opt"`
	CommonElem     *CommonElem     `protobuf:"bytes,53,opt"`
	_              [0]func()
}

type Text struct {
	TextMsg   proto.Option[string] `protobuf:"bytes,1,opt"`
	Link      proto.Option[string] `protobuf:"bytes,2,opt"`
	Attr6Buf  []byte               `protobuf:"bytes,3,opt"`
	Attr7Buf  []byte               `protobuf:"bytes,4,opt"`
	Buf       []byte               `protobuf:"bytes,11,opt"`
	PbReserve []byte               `protobuf:"bytes,12,opt"`
}

type NotOnlineImage struct {
	FilePath       []byte               `protobuf:"bytes,1,opt"`
	FileLen        proto.Option[uint32] `protobuf:"varint,2,opt"`
	DownloadPath   []byte               `protobuf:"bytes,3,opt"`
	OldVerSendFile []byte               `protobuf:"bytes,4,opt"`
	ImgType        proto.Option[uint32] `protobuf:"varint,5,opt"`
	PreviewsImage  []byte               `protobuf:"bytes,6,opt"`
	PicMd5         []byte               `protobuf:"bytes,7,opt"`
	PicHeight      proto.Option[uint32] `protobuf:"varint,8,opt"`
	PicWidth       proto.Option[uint32] `protobuf:"varint,9,opt"`
	ResId          []byte               `protobuf:"bytes,10,opt"`
	Flag           []byte               `protobuf:"bytes,11,opt"`
	ThumbUrl       proto.Option[string] `protobuf:"bytes,12,opt"`
	Original       proto.Option[uint32] `protobuf:"varint,13,opt"`
	BigUrl         proto.Option[string] `protobuf:"bytes,14,opt"`
	OrigUrl        proto.Option[string] `protobuf:"bytes,15,opt"`
	BizType        proto.Option[uint32] `protobuf:"varint,16,opt"`
	Result         proto.Option[uint32] `protobuf:"varint,17,opt"`
	Index          proto.Option[uint32] `protobuf:"varint,18,opt"`
	OpFaceBuf      []byte               `protobuf:"bytes,19,opt"`
	OldPicMd5      proto.Option[bool]   `protobuf:"varint,20,opt"`
	ThumbWidth     proto.Option[uint32] `protobuf:"varint,21,opt"`
	ThumbHeight    proto.Option[uint32] `protobuf:"varint,22,opt"`
	FileId         proto.Option[uint32] `protobuf:"varint,23,opt"`
	ShowLen        proto.Option[uint32] `protobuf:"varint,24,opt"`
	DownloadLen    proto.Option[uint32] `protobuf:"varint,25,opt"`
	Url400         proto.Option[string] `protobuf:"bytes,26,opt"`
	Width400       proto.Option[uint32] `protobuf:"varint,27,opt"`
	Height400      proto.Option[uint32] `protobuf:"varint,28,opt"`
	PbReserve      []byte               `protobuf:"bytes,29,opt"`
}

type TransElem struct {
	ElemType  proto.Option[uint32] `protobuf:"varint,1,opt"`
	ElemValue []byte               `protobuf:"bytes,2,opt"`
}

type CustomFace struct {
	Guid        []byte               `protobuf:"bytes,1,opt"`
	FilePath    proto.Option[string] `protobuf:"bytes,2,opt"`
	Shortcut    proto.Option[string] `protobuf:"bytes,3,opt"`
	Buffer      []byte               `protobuf:"bytes,4,opt"`
	Flag        []byte               `protobuf:"bytes,5,opt"`
	OldData     []byte               `protobuf:"bytes,6,opt"`
	FileId      proto.Option[uint32] `protobuf:"varint,7,opt"`
	ServerIp    proto.Option[int32]  `protobuf:"varint,8,opt"`
	ServerPort  proto.Option[int32]  `protobuf:"varint,9,opt"`
	FileType    proto.Option[int32]  `protobuf:"varint,10,opt"`
	Signature   []byte               `protobuf:"bytes,11,opt"`
	Useful      proto.Option[int32]  `protobuf:"varint,12,opt"`
	Md5         []byte               `protobuf:"bytes,13,opt"`
	ThumbUrl    proto.Option[string] `protobuf:"bytes,14,opt"`
	BigUrl      proto.Option[string] `protobuf:"bytes,15,opt"`
	OrigUrl     proto.Option[string] `protobuf:"bytes,16,opt"`
	BizType     proto.Option[int32]  `protobuf:"varint,17,opt"`
	RepeatIndex proto.Option[int32]  `protobuf:"varint,18,opt"`
	RepeatImage proto.Option[int32]  `protobuf:"varint,19,opt"`
	ImageType   proto.Option[int32]  `protobuf:"varint,20,opt"`
	Index       proto.Option[int32]  `protobuf:"varint,21,opt"`
	Width       proto.Option[int32]  `protobuf:"varint,22,opt"`
	Height      proto.Option[int32]  `protobuf:"varint,23,opt"`
	Source      proto.Option[int32]  `protobuf:"varint,24,opt"`
	Size        proto.Option[uint32] `protobuf:"varint,25,opt"`
	Origin      proto.Option[int32]  `protobuf:"varint,26,opt"`
	ThumbWidth  proto.Option[int32]  `protobuf:"varint,27,opt"`
	ThumbHeight proto.Option[int32]  `protobuf:"varint,28,opt"`
	ShowLen     proto.Option[int32]  `protobuf:"varint,29,opt"`
	DownloadLen proto.Option[int32]  `protobuf:"varint,30,opt"`
	X400Url     proto.Option[string] `protobuf:"bytes,31,opt"`
	X400Width   proto.Option[int32]  `protobuf:"varint,32,opt"`
	X400Height  proto.Option[int32]  `protobuf:"varint,33,opt"`
	PbReserve   *PbReserve1          `protobuf:"bytes,34,opt"`
}

type RichMsg struct {
	BytesTemplate1 []byte               `protobuf:"bytes,1,opt"`
	ServiceId      proto.Option[uint32] `protobuf:"varint,2,opt"`
	BytesMsgResid  []byte               `protobuf:"bytes,3,opt"`
	Rand           proto.Option[uint32] `protobuf:"varint,4,opt"`
	Seq            proto.Option[uint32] `protobuf:"varint,5,opt"`
	Flags          proto.Option[uint32] `protobuf:"varint,6,opt"`
}

type VideoFile struct {
	FileUuid               proto.Option[string] `protobuf:"bytes,1,opt"`
	FileMd5                []byte               `protobuf:"bytes,2,opt"`
	FileName               proto.Option[string] `protobuf:"bytes,3,opt"`
	FileFormat             proto.Option[int32]  `protobuf:"varint,4,opt"`
	FileTime               proto.Option[int32]  `protobuf:"varint,5,opt"`
	FileSize               proto.Option[int32]  `protobuf:"varint,6,opt"`
	ThumbWidth             proto.Option[int32]  `protobuf:"varint,7,opt"`
	ThumbHeight            proto.Option[int32]  `protobuf:"varint,8,opt"`
	ThumbFileMd5           []byte               `protobuf:"bytes,9,opt"`
	Source                 []byte               `protobuf:"bytes,10,opt"`
	ThumbFileSize          proto.Option[int32]  `protobuf:"varint,11,opt"`
	BusiType               proto.Option[int32]  `protobuf:"varint,12,opt"`
	FromChatType           proto.Option[int32]  `protobuf:"varint,13,opt"`
	ToChatType             proto.Option[int32]  `protobuf:"varint,14,opt"`
	BoolSupportProgressive proto.Option[bool]   `protobuf:"varint,15,opt"`
	FileWidth              proto.Option[int32]  `protobuf:"varint,16,opt"`
	FileHeight             proto.Option[int32]  `protobuf:"varint,17,opt"`
	SubBusiType            proto.Option[int32]  `protobuf:"varint,18,opt"`
	VideoAttr              proto.Option[int32]  `protobuf:"varint,19,opt"`
	BytesThumbFileUrls     [][]byte             `protobuf:"bytes,20,rep"`
	BytesVideoFileUrls     [][]byte             `protobuf:"bytes,21,rep"`
	ThumbDownloadFlag      proto.Option[int32]  `protobuf:"varint,22,opt"`
	VideoDownloadFlag      proto.Option[int32]  `protobuf:"varint,23,opt"`
	PbReserve              []byte               `protobuf:"bytes,24,opt"`
}

type SourceMsg struct {
	OrigSeqs  []uint64             `protobuf:"varint,1,rep"`
	SenderUin proto.Option[uint64] `protobuf:"varint,2,opt"`
	Time      proto.Option[uint32] `protobuf:"varint,3,opt"`
	Flag      proto.Option[uint32] `protobuf:"varint,4,opt"`
	Elems     []*Elem              `protobuf:"bytes,5,rep"`
	Type      proto.Option[uint32] `protobuf:"varint,6,opt"`
	RichMsg   []byte               `protobuf:"bytes,7,opt"`
	PbReserve []byte               `protobuf:"bytes,8,opt"`
	SrcMsg    []byte               `protobuf:"bytes,9,opt"`
	ToUin     proto.Option[uint64] `protobuf:"varint,10,opt"`
	TroopName []byte               `protobuf:"bytes,11,opt"`
}

type LightAppElem struct {
	BytesData     []byte `protobuf:"bytes,1,opt"`
	BytesMsgResid []byte `protobuf:"bytes,2,opt"`
}

type CommonElem struct {
	ServiceType  proto.Option[uint32] `protobuf:"varint,1,opt"`
	PbElem       []byte               `protobuf:"bytes,2,opt"`
	BusinessType proto.Option[uint32] `protobuf:"varint,3,opt"`
}

type FileExtra struct {
	File *NotOnlineFile `protobuf:"bytes,1,opt"`
	_    [0]func()
}

type TextResvAttr struct {
	Wording            proto.Option[string] `protobuf:"bytes,1,opt"`
	TextAnalysisResult proto.Option[uint32] `protobuf:"varint,2,opt"`
	AtType             proto.Option[uint32] `protobuf:"varint,3,opt"`
	AtMemberUin        proto.Option[uint64] `protobuf:"varint,4,opt"`
	AtMemberTinyid     proto.Option[uint64] `protobuf:"varint,5,opt"`
	AtMemberRoleInfo   *RoleInfo            `protobuf:"bytes,6,opt"`
	AtRoleInfo         *RoleInfo            `protobuf:"bytes,7,opt"`
	AtChannelInfo      *ChannelInfo         `protobuf:"bytes,8,opt"`
	AtMemberUid        proto.Option[string] `protobuf:"bytes,9,opt"`
	_                  [0]func()
}

type ChannelInfo struct {
	GuildId   proto.Option[uint64] `protobuf:"varint,1,opt"`
	ChannelId proto.Option[uint64] `protobuf:"varint,2,opt"`
	_         [0]func()
}

type RoleInfo struct {
	_ [0]func()
}

type SourceMsgResvAttr struct {
	OriMsgType  proto.Option[uint32] `protobuf:"varint,2,opt"`
	SourceMsgId proto.Option[uint64] `protobuf:"varint,3,opt"`
	SenderUid   proto.Option[string] `protobuf:"bytes,6,opt"`
	ReceiverUid proto.Option[string] `protobuf:"bytes,7,opt"`
	_           [0]func()
}

type GroupFileExtra struct {
	Field1   proto.Option[uint32] `protobuf:"varint,1,opt"`
	FileName proto.Option[string] `protobuf:"bytes,2,opt"`
	Display  proto.Option[string] `protobuf:"bytes,3,opt"`
	Inner    *GroupFileExtraInner `protobuf:"bytes,7,opt"`
	_        [0]func()
}

type GroupFileExtraInner struct {
	Info *GroupFileExtraInfo `protobuf:"bytes,2,opt"`
	_    [0]func()
}

type GroupFileExtraInfo struct {
	BusId    proto.Option[uint32] `protobuf:"varint,1,opt"`
	FileId   proto.Option[string] `protobuf:"bytes,2,opt"`
	FileSize proto.Option[int64]  `protobuf:"varint,3,opt"`
	FileName proto.Option[string] `protobuf:"bytes,4,opt"`
	Field5   proto.Option[uint32] `protobuf:"varint,5,opt"`
	Field7   proto.Option[string] `protobuf:"bytes,7,opt"`
	FileMd5  proto.Option[string] `protobuf:"bytes,8,opt"`
	_        [0]func()
}

type FeedsInfo struct {
	BusId     proto.Option[uint32] `protobuf:"varint,1,opt"`
	FileId    proto.Option[string] `protobuf:"bytes,2,opt"`
	MsgRandom proto.Option[uint32] `protobuf:"varint,3,opt"`
	Ext       []byte               `protobuf:"bytes,4,opt"`
	FeedFlag  proto.Option[uint32] `protobuf:"varint,5,opt"`
}

type FeedsResult struct {
	RetCode  proto.Option[int32]  `protobuf:"varint,1,opt"`
	Detail   proto.Option[string] `protobuf:"bytes,2,opt"`
	FileId   proto.Option[string] `protobuf:"bytes,3,opt"`
	BusId    proto.Option[uint32] `protobuf:"varint,4,opt"`
	DeadTime proto.Option[uint32] `protobuf:"varint,5,opt"`
	_        [0]func()
}

type FileInfo struct {
	FileId         proto.Option[string] `protobuf:"bytes,1,opt"`
	FileName       proto.Option[string] `protobuf:"bytes,2,opt"`
	FileSize       proto.Option[uint64] `protobuf:"varint,3,opt"`
	BusId          proto.Option[uint32] `protobuf:"varint,4,opt"`
	UploadedSize   proto.Option[uint64] `protobuf:"varint,5,opt"`
	UploadTime     proto.Option[uint32] `protobuf:"varint,6,opt"`
	DeadTime       proto.Option[uint32] `protobuf:"varint,7,opt"`
	ModifyTime     proto.Option[uint32] `protobuf:"varint,8,opt"`
	DownloadTimes  proto.Option[uint32] `protobuf:"varint,9,opt"`
	Sha            []byte               `protobuf:"bytes,10,opt"`
	Sha3           []byte               `protobuf:"bytes,11,opt"`
	Md5            []byte               `protobuf:"bytes,12,opt"`
	LocalPath      proto.Option[string] `protobuf:"bytes,13,opt"`
	UploaderName   proto.Option[string] `protobuf:"bytes,14,opt"`
	UploaderUin    proto.Option[uint64] `protobuf:"varint,15,opt"`
	ParentFolderId proto.Option[string] `protobuf:"bytes,16,opt"`
	SafeType       proto.Option[uint32] `protobuf:"varint,17,opt"`
	FileBlobExt    []byte               `protobuf:"bytes,20,opt"`
	OwnerUin       proto.Option[uint64] `protobuf:"varint,21,opt"`
	FeedId         proto.Option[string] `protobuf:"bytes,22,opt"`
	ReservedField  []byte               `protobuf:"bytes,23,opt"`
}

type FileInfoTmem struct {
	GroupCode proto.Option[uint64] `protobuf:"varint,1,opt"`
	Files     []*FileInfo          `protobuf:"bytes,2,rep"`
}

type FileItem struct {
	Type       proto.Option[uint32] `protobuf:"varint,1,opt"`
	FolderInfo *FolderInfo          `protobuf:"bytes,2,opt"`
	FileInfo   *FileInfo            `protobuf:"bytes,3,opt"`
	_          [0]func()
}

type FolderInfo struct {
	FolderId       proto.Option[string] `protobuf:"bytes,1,opt"`
	ParentFolderId proto.Option[string] `protobuf:"bytes,2,opt"`
	FolderName     proto.Option[string] `protobuf:"bytes,3,opt"`
	CreateTime     proto.Option[uint32] `protobuf:"varint,4,opt"`
	ModifyTime     proto.Option[uint32] `protobuf:"varint,5,opt"`
	CreateUin      proto.Option[uint64] `protobuf:"varint,6,opt"`
	CreatorName    proto.Option[string] `protobuf:"bytes,7,opt"`
	TotalFileCount proto.Option[uint32] `protobuf:"varint,8,opt"`
	ModifyUin      proto.Option[uint64] `protobuf:"varint,9,opt"`
	ModifyName     proto.Option[string] `protobuf:"bytes,10,opt"`
	UsedSpace      proto.Option[uint64] `protobuf:"varint,11,opt"`
	_              [0]func()
}

type FolderInfoItem struct {
	GroupCode proto.Option[uint64] `protobuf:"varint,1,opt"`
	Folders   []*FolderInfo        `protobuf:"bytes,2,rep"`
}

type OverwriteInfo struct {
	FileId        proto.Option[string] `protobuf:"bytes,1,opt"`
	DownloadTimes proto.Option[uint32] `protobuf:"varint,2,opt"`
	_             [0]func()
}

type PbMultiMsgTransmit struct {
	Messages []*CommonMessage  `protobuf:"bytes,1,rep"`
	Items    []*PbMultiMsgItem `protobuf:"bytes,2,rep"`
}

type PbMultiMsgItem struct {
	FileName proto.Option[string] `protobuf:"bytes,1,opt"`
	Buffer   *PbMultiMsgNew       `protobuf:"bytes,2,opt"`
	_        [0]func()
}

type PbMultiMsgNew struct {
	Msg []*CommonMessage `protobuf:"bytes,1,rep"`
}

type LongMsgInterfaceReq struct {
	RecvReq *LongMsgRecvReq `protobuf:"bytes,1,opt"`
	SendReq *LongMsgSendReq `protobuf:"bytes,2,opt"`
	Attr    *LongMsgAttr    `protobuf:"bytes,15,opt"`
	_       [0]func()
}

type LongMsgInterfaceRsp struct {
	RecvRsp *LongMsgRecvRsp `protobuf:"bytes,1,opt"`
	SendRsp *LongMsgSendRsp `protobuf:"bytes,2,opt"`
	Attr    *LongMsgAttr    `protobuf:"bytes,15,opt"`
	_       [0]func()
}

type LongMsgAttr struct {
	SubCmd     proto.Option[uint32] `protobuf:"varint,1,opt"`
	ClientType proto.Option[uint32] `protobuf:"varint,2,opt"`
	Platform   proto.Option[uint32] `protobuf:"varint,3,opt"`
	ProxyType  proto.Option[uint32] `protobuf:"varint,4,opt"`
	_          [0]func()
}

type LongMsgPeerInfo struct {
	PeerUid proto.Option[string] `protobuf:"bytes,2,opt"`
	_       [0]func()
}

type LongMsgRecvReq struct {
	PeerInfo *LongMsgPeerInfo     `protobuf:"bytes,1,opt"`
	ResId    proto.Option[string] `protobuf:"bytes,2,opt"`
	MsgType  proto.Option[uint32] `protobuf:"varint,3,opt"`
	_        [0]func()
}

type LongMsgSendReq struct {
	MsgType  proto.Option[uint32] `protobuf:"varint,1,opt"`
	PeerInfo *LongMsgPeerInfo     `protobuf:"bytes,2,opt"`
	GroupUin proto.Option[int64]  `protobuf:"varint,3,opt"`
	Payload  []byte               `protobuf:"bytes,4,opt"`
}

type LongMsgSendRsp struct {
	ResId proto.Option[string] `protobuf:"bytes,3,opt"`
	_     [0]func()
}

type LongMsgRecvRsp struct {
	ResId   proto.Option[string] `protobuf:"bytes,3,opt"`
	Payload []byte               `protobuf:"bytes,4,opt"`
}

type CommonMessage struct {
	RoutingHead *RoutingHead `protobuf:"bytes,1,opt"`
	ContentHead *ContentHead `protobuf:"bytes,2,opt"`
	MessageBody *MessageBody `protobuf:"bytes,3,opt"`
	_           [0]func()
}

type ContentHead struct {
	Type           proto.Option[int32]  `protobuf:"varint,1,opt"`
	SubType        proto.Option[int32]  `protobuf:"varint,2,opt"`
	C2CCommand     proto.Option[int32]  `protobuf:"varint,3,opt"`
	Random         proto.Option[uint32] `protobuf:"varint,4,opt"`
	Sequence       proto.Option[uint64] `protobuf:"varint,5,opt"`
	Time           proto.Option[int64]  `protobuf:"varint,6,opt"`
	PkgNum         proto.Option[int32]  `protobuf:"varint,7,opt"`
	PkgIndex       proto.Option[int32]  `protobuf:"varint,8,opt"`
	DivSeq         proto.Option[int32]  `protobuf:"varint,9,opt"`
	AutoReply      proto.Option[int32]  `protobuf:"varint,10,opt"`
	ClientSequence proto.Option[uint64] `protobuf:"varint,11,opt"`
	MsgUid         proto.Option[uint64] `protobuf:"varint,12,opt"`
	_              [0]func()
}

type RoutingHead struct {
	FromUin    proto.Option[int64]  `protobuf:"varint,1,opt"`
	FromUid    proto.Option[string] `protobuf:"bytes,2,opt"`
	FromAppId  proto.Option[int32]  `protobuf:"varint,3,opt"`
	FromInstId proto.Option[int32]  `protobuf:"varint,4,opt"`
	ToUin      proto.Option[int64]  `protobuf:"varint,5,opt"`
	ToUid      proto.Option[string] `protobuf:"bytes,6,opt"`
	CommonC2C  *CommonC2C           `protobuf:"bytes,7,opt"`
	Group      *CommonGroup         `protobuf:"bytes,8,opt"`
	_          [0]func()
}

type CommonC2C struct {
	C2CType     proto.Option[int32]  `protobuf:"varint,1,opt"`
	ServiceType proto.Option[int32]  `protobuf:"varint,2,opt"`
	Sig         []byte               `protobuf:"bytes,3,opt"`
	FromTinyId  proto.Option[int64]  `protobuf:"varint,4,opt"`
	ToTinyId    proto.Option[int64]  `protobuf:"varint,5,opt"`
	Name        proto.Option[string] `protobuf:"bytes,6,opt"`
}

type CommonGroup struct {
	GroupCode       proto.Option[int64]  `protobuf:"varint,1,opt"`
	GroupType       proto.Option[int32]  `protobuf:"varint,2,opt"`
	GroupInfoSeq    proto.Option[int64]  `protobuf:"varint,3,opt"`
	GroupCard       proto.Option[string] `protobuf:"bytes,4,opt"`
	GroupCardType   proto.Option[int32]  `protobuf:"varint,5,opt"`
	GroupLevel      proto.Option[int32]  `protobuf:"varint,6,opt"`
	GroupName       proto.Option[string] `protobuf:"bytes,7,opt"`
	ExtGroupKeyInfo proto.Option[string] `protobuf:"bytes,8,opt"`
	MsgFlag         proto.Option[int32]  `protobuf:"varint,9,opt"`
	_               [0]func()
}

type MessageBody struct {
	RichText          *RichText `protobuf:"bytes,1,opt"`
	MsgContent        []byte    `protobuf:"bytes,2,opt"`
	MsgEncryptContent []byte    `protobuf:"bytes,3,opt"`
}

type RichText struct {
	Attr           *Attr           `protobuf:"bytes,1,opt"`
	Elems          []*Elem         `protobuf:"bytes,2,rep"`
	NotOnlineFile  *NotOnlineFile  `protobuf:"bytes,3,opt"`
	Ptt            *Ptt            `protobuf:"bytes,4,opt"`
	TmpPtt         *TmpPtt         `protobuf:"bytes,5,opt"`
	Trans211TmpMsg *Trans211TmpMsg `protobuf:"bytes,6,opt"`
}

type Attr struct {
	CodePage       proto.Option[int32]  `protobuf:"varint,1,opt"`
	Time           proto.Option[int32]  `protobuf:"varint,2,opt"`
	PlayModeRandom proto.Option[int32]  `protobuf:"varint,3,opt"`
	Color          proto.Option[int32]  `protobuf:"varint,4,opt"`
	Size           proto.Option[int32]  `protobuf:"varint,5,opt"`
	TabEffect      proto.Option[int32]  `protobuf:"varint,6,opt"`
	CharSet        proto.Option[int32]  `protobuf:"varint,7,opt"`
	PitchAndFamily proto.Option[int32]  `protobuf:"varint,8,opt"`
	FontName       proto.Option[string] `protobuf:"bytes,9,opt"`
	ReserveData    []byte               `protobuf:"bytes,10,opt"`
}

type NotOnlineFile struct {
	FileType       proto.Option[uint32] `protobuf:"varint,1,opt"`
	Sig            []byte               `protobuf:"bytes,2,opt"`
	FileUuid       proto.Option[string] `protobuf:"bytes,3,opt"`
	FileMd5        []byte               `protobuf:"bytes,4,opt"`
	FileName       proto.Option[string] `protobuf:"bytes,5,opt"`
	FileSize       proto.Option[uint64] `protobuf:"varint,6,opt"`
	Note           []byte               `protobuf:"bytes,7,opt"`
	Reserved       proto.Option[uint32] `protobuf:"varint,8,opt"`
	SubCmd         proto.Option[uint32] `protobuf:"varint,9,opt"`
	MicroCloud     proto.Option[uint32] `protobuf:"varint,10,opt"`
	FileUrls       [][]byte             `protobuf:"bytes,11,rep"`
	DownloadFlag   proto.Option[uint32] `protobuf:"varint,12,opt"`
	DangerLevel    proto.Option[uint32] `protobuf:"varint,50,opt"`
	LifeTime       proto.Option[uint32] `protobuf:"varint,51,opt"`
	UploadTime     proto.Option[uint32] `protobuf:"varint,52,opt"`
	AbsFileType    proto.Option[uint32] `protobuf:"varint,53,opt"`
	ClientType     proto.Option[uint32] `protobuf:"varint,54,opt"`
	ExpireTime     proto.Option[uint32] `protobuf:"varint,55,opt"`
	PbReserve      []byte               `protobuf:"bytes,56,opt"`
	FileIdCrcMedia proto.Option[string] `protobuf:"bytes,57,opt"`
}

type Ptt struct {
	FileType      proto.Option[uint32] `protobuf:"varint,1,opt"`
	SrcUin        proto.Option[uint64] `protobuf:"varint,2,opt"`
	FileUuid      []byte               `protobuf:"bytes,3,opt"`
	FileMd5       []byte               `protobuf:"bytes,4,opt"`
	FileName      proto.Option[string] `protobuf:"bytes,5,opt"`
	FileSize      proto.Option[uint32] `protobuf:"varint,6,opt"`
	Reserve       []byte               `protobuf:"bytes,7,opt"`
	FileId        proto.Option[uint32] `protobuf:"varint,8,opt"`
	ServerIp      proto.Option[uint32] `protobuf:"varint,9,opt"`
	ServerPort    proto.Option[uint32] `protobuf:"varint,10,opt"`
	Valid         proto.Option[bool]   `protobuf:"varint,11,opt"`
	Signature     []byte               `protobuf:"bytes,12,opt"`
	Shortcut      []byte               `protobuf:"bytes,13,opt"`
	FileKey       proto.Option[string] `protobuf:"bytes,14,opt"`
	MagicPttIndex proto.Option[uint32] `protobuf:"varint,15,opt"`
	VoiceSwitch   proto.Option[uint32] `protobuf:"varint,16,opt"`
	PttUrl        []byte               `protobuf:"bytes,17,opt"`
	GroupFileKey  []byte               `protobuf:"bytes,18,opt"`
	Time          proto.Option[uint32] `protobuf:"varint,19,opt"`
	DownPara      []byte               `protobuf:"bytes,20,opt"`
	Format        proto.Option[uint32] `protobuf:"varint,29,opt"`
	PbReserve     []byte               `protobuf:"bytes,30,opt"`
	PttUrls       [][]byte             `protobuf:"bytes,31,rep"`
	DownloadFlag  proto.Option[uint32] `protobuf:"varint,32,opt"`
}

type TmpPtt struct {
	FileType      proto.Option[uint32] `protobuf:"varint,1,opt"`
	FileUuid      []byte               `protobuf:"bytes,2,opt"`
	FileMd5       []byte               `protobuf:"bytes,3,opt"`
	FileName      []byte               `protobuf:"bytes,4,opt"`
	FileSize      proto.Option[uint32] `protobuf:"varint,5,opt"`
	PttTimes      proto.Option[uint32] `protobuf:"varint,6,opt"`
	UserType      proto.Option[uint32] `protobuf:"varint,7,opt"`
	PttTransFlag  proto.Option[uint32] `protobuf:"varint,8,opt"`
	BusiType      proto.Option[uint32] `protobuf:"varint,9,opt"`
	MsgId         proto.Option[uint64] `protobuf:"varint,10,opt"`
	PbReserve     []byte               `protobuf:"bytes,30,opt"`
	PttEncodeData []byte               `protobuf:"bytes,31,opt"`
}

type Trans211TmpMsg struct {
	MsgBody []byte               `protobuf:"bytes,1,opt"`
	C2CCmd  proto.Option[uint32] `protobuf:"varint,2,opt"`
}

type MsgPush struct {
	CommonMessage  *CommonMessage     `protobuf:"bytes,1,opt"`
	PushNotifyFlag proto.Option[bool] `protobuf:"varint,5,opt"`
	_              [0]func()
}

type PbSendMsgReq struct {
	RoutingHead    *SendRoutingHead     `protobuf:"bytes,1,opt"`
	ContentHead    *SendContentHead     `protobuf:"bytes,2,opt"`
	MessageBody    *MessageBody         `protobuf:"bytes,3,opt"`
	ClientSequence proto.Option[uint64] `protobuf:"varint,4,opt"`
	Random         proto.Option[uint32] `protobuf:"varint,5,opt"`
	_              [0]func()
}

type PbSendMsgResp struct {
	Result         proto.Option[int32]  `protobuf:"varint,1,opt"`
	ErrMsg         proto.Option[string] `protobuf:"bytes,2,opt"`
	SendTime       proto.Option[int64]  `protobuf:"varint,3,opt"`
	MsgInfoFlag    proto.Option[uint32] `protobuf:"varint,10,opt"`
	Sequence       proto.Option[uint64] `protobuf:"varint,11,opt"`
	ClientSequence proto.Option[uint64] `protobuf:"varint,14,opt"`
	_              [0]func()
}

type SendContentHead struct {
	PkgNum    proto.Option[uint32] `protobuf:"varint,1,opt"`
	PkgIndex  proto.Option[uint32] `protobuf:"varint,2,opt"`
	DivSeq    proto.Option[uint32] `protobuf:"varint,3,opt"`
	AutoReply proto.Option[uint32] `protobuf:"varint,4,opt"`
	_         [0]func()
}

type SendRoutingHead struct {
	C2C        *C2C        `protobuf:"bytes,1,opt"`
	Group      *Grp        `protobuf:"bytes,2,opt"`
	Trans0X211 *Trans0X211 `protobuf:"bytes,15,opt"`
	_          [0]func()
}

type C2C struct {
	PeerUin proto.Option[int64]  `protobuf:"varint,1,opt"`
	PeerUid proto.Option[string] `protobuf:"bytes,2,opt"`
	_       [0]func()
}

type Grp struct {
	GroupUin proto.Option[int64] `protobuf:"varint,1,opt"`
	_        [0]func()
}

type Trans0X211 struct {
	ToUin proto.Option[int64]  `protobuf:"varint,1,opt"`
	CcCmd proto.Option[uint32] `protobuf:"varint,2,opt"`
	Uid   proto.Option[string] `protobuf:"bytes,8,opt"`
	_     [0]func()
}

type SsoC2CRecallMsgReq struct {
	Type      proto.Option[uint32]        `protobuf:"varint,1,opt"`
	TargetUid proto.Option[string]        `protobuf:"bytes,3,opt"`
	Info      *SsoC2CRecallMsgReqInfo     `protobuf:"bytes,4,opt"`
	Settings  *SsoC2CRecallMsgReqSettings `protobuf:"bytes,5,opt"`
	Field6    proto.Option[bool]          `protobuf:"varint,6,opt"`
	_         [0]func()
}

type SsoC2CRecallMsgReqInfo struct {
	Sequence       proto.Option[uint64] `protobuf:"varint,1,opt"`
	Random         proto.Option[uint32] `protobuf:"varint,2,opt"`
	MessageId      proto.Option[uint64] `protobuf:"varint,3,opt"`
	Timestamp      proto.Option[uint32] `protobuf:"varint,4,opt"`
	Field5         proto.Option[uint32] `protobuf:"varint,5,opt"`
	ClientSequence proto.Option[uint64] `protobuf:"varint,6,opt"`
	_              [0]func()
}

type SsoC2CRecallMsgReqSettings struct {
	Field1 proto.Option[bool] `protobuf:"varint,1,opt"`
	Field2 proto.Option[bool] `protobuf:"varint,2,opt"`
	_      [0]func()
}

type SsoGetC2CMsgReq struct {
	PeerUin       proto.Option[int64]  `protobuf:"varint,1,opt"`
	PeerUid       proto.Option[string] `protobuf:"bytes,2,opt"`
	StartSequence proto.Option[uint64] `protobuf:"varint,3,opt"`
	EndSequence   proto.Option[uint64] `protobuf:"varint,4,opt"`
	_             [0]func()
}

type SsoGetC2CMsgRsp struct {
	Retcode       proto.Option[uint32] `protobuf:"varint,1,opt"`
	Message       proto.Option[string] `protobuf:"bytes,2,opt"`
	StartSequence proto.Option[uint64] `protobuf:"varint,3,opt"`
	EndSequence   proto.Option[uint64] `protobuf:"varint,4,opt"`
	Messages      []*CommonMessage     `protobuf:"bytes,7,rep"`
}

type SsoGetGroupMsg struct {
	Info   *SsoGetGroupMsgInfo  `protobuf:"bytes,1,opt"`
	Filter proto.Option[uint32] `protobuf:"varint,2,opt"`
	_      [0]func()
}

type SsoGetGroupMsgInfo struct {
	GroupUin      proto.Option[int64]  `protobuf:"varint,1,opt"`
	StartSequence proto.Option[uint64] `protobuf:"varint,2,opt"`
	EndSequence   proto.Option[uint64] `protobuf:"varint,3,opt"`
	_             [0]func()
}

type SsoGetGroupMsgRsp struct {
	RetCode  proto.Option[uint32]   `protobuf:"varint,1,opt"`
	ErrorMsg proto.Option[string]   `protobuf:"bytes,2,opt"`
	Body     *SsoGetGroupMsgRspBody `protobuf:"bytes,3,opt"`
	_        [0]func()
}

type SsoGetGroupMsgRspBody struct {
	Retcode       proto.Option[uint32] `protobuf:"varint,1,opt"`
	Message       proto.Option[string] `protobuf:"bytes,2,opt"`
	GroupUin      proto.Option[uint32] `protobuf:"varint,3,opt"`
	StartSequence proto.Option[uint64] `protobuf:"varint,4,opt"`
	EndSequence   proto.Option[uint64] `protobuf:"varint,5,opt"`
	Messages      []*CommonMessage     `protobuf:"bytes,6,rep"`
}

type SsoGetRoamMsgReq struct {
	PeerUid   proto.Option[string] `protobuf:"bytes,1,opt"`
	Time      proto.Option[uint32] `protobuf:"varint,2,opt"`
	Random    proto.Option[uint32] `protobuf:"varint,3,opt"`
	Count     proto.Option[uint32] `protobuf:"varint,4,opt"`
	Direction proto.Option[uint32] `protobuf:"varint,5,opt"`
	_         [0]func()
}

type SsoGetRoamMsgRsp struct {
	PeerUid    proto.Option[string] `protobuf:"bytes,3,opt"`
	IsComplete proto.Option[bool]   `protobuf:"varint,4,opt"`
	Timestamp  proto.Option[uint32] `protobuf:"varint,5,opt"`
	Random     proto.Option[uint32] `protobuf:"varint,6,opt"`
	Messages   []*CommonMessage     `protobuf:"bytes,7,rep"`
}

type SsoGroupRecallMsgReq struct {
	Type     proto.Option[uint32]        `protobuf:"varint,1,opt"`
	GroupUin proto.Option[int64]         `protobuf:"varint,2,opt"`
	Field3   *SsoGroupRecallMsgReqField3 `protobuf:"bytes,3,opt"`
	Field4   *SsoGroupRecallMsgReqField4 `protobuf:"bytes,4,opt"`
	_        [0]func()
}

type SsoGroupRecallMsgReqField3 struct {
	Sequence proto.Option[uint64] `protobuf:"varint,1,opt"`
	Random   proto.Option[uint32] `protobuf:"varint,2,opt"`
	Field3   proto.Option[uint32] `protobuf:"varint,3,opt"`
	_        [0]func()
}

type SsoGroupRecallMsgReqField4 struct {
	Field1 proto.Option[uint32] `protobuf:"varint,1,opt"`
	_      [0]func()
}

type PbReserve1 struct {
	SubType proto.Option[int32]  `protobuf:"varint,1,opt"`
	Field3  proto.Option[int32]  `protobuf:"varint,3,opt"`
	Field4  proto.Option[int32]  `protobuf:"varint,4,opt"`
	Summary proto.Option[string] `protobuf:"bytes,9,opt"`
	Field10 proto.Option[int32]  `protobuf:"varint,10,opt"`
	Field21 *PbReserve2          `protobuf:"bytes,21,opt"`
	Field31 proto.Option[string] `protobuf:"bytes,31,opt"`
	_       [0]func()
}

type PbReserve2 struct {
	Field1 proto.Option[int32]  `protobuf:"varint,1,opt"`
	Field2 proto.Option[string] `protobuf:"bytes,2,opt"`
	Field3 proto.Option[int32]  `protobuf:"varint,3,opt"`
	Field4 proto.Option[int32]  `protobuf:"varint,4,opt"`
	Field5 proto.Option[int32]  `protobuf:"varint,5,opt"`
	Md5Str proto.Option[string] `protobuf:"bytes,7,opt"`
	_      [0]func()
}
