// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: message/old_code_message.proto

package message

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type Face struct {
	Index proto.Option[int32] `protobuf:"varint,1,opt"`
	Old   []byte              `protobuf:"bytes,2,opt"`
	Buf   []byte              `protobuf:"bytes,11,opt"`
}

type MarketFace struct {
	FaceName    proto.Option[string] `protobuf:"bytes,1,opt"`
	ItemType    proto.Option[uint32] `protobuf:"varint,2,opt"`
	FaceInfo    proto.Option[uint32] `protobuf:"varint,3,opt"`
	FaceId      []byte               `protobuf:"bytes,4,opt"`
	TabId       proto.Option[uint32] `protobuf:"varint,5,opt"`
	SubType     proto.Option[uint32] `protobuf:"varint,6,opt"`
	Key         []byte               `protobuf:"bytes,7,opt"`
	Param       []byte               `protobuf:"bytes,8,opt"`
	MediaType   proto.Option[uint32] `protobuf:"varint,9,opt"`
	ImageWidth  proto.Option[uint32] `protobuf:"varint,10,opt"`
	ImageHeight proto.Option[uint32] `protobuf:"varint,11,opt"`
	MobileParam []byte               `protobuf:"bytes,12,opt"`
	PbReserve   []byte               `protobuf:"bytes,13,opt"`
}

type FaceExtra struct {
	FaceId proto.Option[int32] `protobuf:"varint,1,opt"`
	_      [0]func()
}

type QSmallFaceExtra struct {
	FaceId   proto.Option[uint32] `protobuf:"varint,1,opt"`
	Preview  proto.Option[string] `protobuf:"bytes,2,opt"`
	Preview2 proto.Option[string] `protobuf:"bytes,3,opt"`
	_        [0]func()
}

type QFaceExtra struct {
	PackId      proto.Option[string] `protobuf:"bytes,1,opt"`
	StickerId   proto.Option[string] `protobuf:"bytes,2,opt"`
	Qsid        proto.Option[int32]  `protobuf:"varint,3,opt"`
	SourceType  proto.Option[int32]  `protobuf:"varint,4,opt"`
	StickerType proto.Option[int32]  `protobuf:"varint,5,opt"`
	ResultId    proto.Option[string] `protobuf:"bytes,6,opt"`
	Text        proto.Option[string] `protobuf:"bytes,7,opt"`
	// optional bytes surprise_id = 8;
	RandomType proto.Option[int32] `protobuf:"varint,9,opt"`
	_          [0]func()
}
